### ISSUE TITLE
Can't generate SQL with an empty selection

### ISSUE THREAD

**Issue by noefroidevaux** [groue/GRDB.swift#1315] opened 2023-01-11 16:57 UTC
First, a big thank you for this amazing library!

I use it with success, but I have a problem with a long/custom request... I am not sure if it is a bug or a limitation in the library.

### What did you do?

`A`, `B`, `C`, `D`, `E`, `F` are structs which are `Codable`, `FetchableRecord`, `PersistableRecord`, `Identifiable` and `Hashable`

```
A belongs to B

B has one C (optional)
C has many D

B has one E (optional)
E has many F
```

AInfo struct:

```
struct AInfo: FetchableRecord, Decodable, Identifiable, Hashable {
  let a: A
  let b: B
  let c: C?
  let dList: [D]
  let e: E?
  let fList: [F]

  [...]
}
```

Request:

```
A.including(
    required: A.b
        .including(
            optional: B.c
                .including(all: C.d)
        )
        .including(
            optional: B.e
                .including(all: E.f)
        )
)
.asRequest(of: AInfo.self)
```
### What did you expect to happen?

`AInfo` struct instance is filled with all data without error

### What happened instead?

A runtime error `Can't generate SQL with an empty selection` happen.

If I remove one of `.including(all: C.d)` or `.including(all: E.f)` it seems working. It's like it doesn't work only when I try to `include(all:)` two times.

### Environment

**GRDB flavor(s):** GRDB
**GRDB version:** 6.6.0
**Installation method:** SPM
**Xcode version:** 14.2
**Swift version:** 5.7.2
**Platform(s) running GRDB:** iOS
**macOS version running Xcode:** 13.1 (Ventura)

**Comment by groue** [comment] 2023-01-11 18:34
Hello @noefroidevaux, thanks for the compliment :-)

It looks like you found a bug indeed, thank you very much 👍 

There is no known workaround :-/

Please hold on until the fix ships! Just in case, did you happen to investigate?

<details><summary>Reproducing code</summary>

```swift
struct A: Codable, FetchableRecord, PersistableRecord {
    static let b = belongsTo(B.self)
}
struct B: Codable, FetchableRecord, PersistableRecord {
    static let c = hasOne(C.self)
    static let e = hasOne(E.self)
}
struct C: Codable, FetchableRecord, PersistableRecord {
    static let ds = hasMany(D.self)
}
struct D: Codable, FetchableRecord, PersistableRecord { }
struct E: Codable, FetchableRecord, PersistableRecord {
    static let fs = hasMany(F.self)
}
struct F: Codable, FetchableRecord, PersistableRecord { }

try DatabaseQueue().write { db in
    try db.execute(sql: """
        CREATE TABLE b (id INTEGER PRIMARY KEY);
        CREATE TABLE a (id INTEGER PRIMARY KEY, bId INTEGER REFERENCES b(id));
        CREATE TABLE c (id INTEGER PRIMARY KEY, bId INTEGER REFERENCES b(id));
        CREATE TABLE d (id INTEGER PRIMARY KEY, cId INTEGER REFERENCES c(id));
        CREATE TABLE e (id INTEGER PRIMARY KEY, bId INTEGER REFERENCES b(id));
        CREATE TABLE f (id INTEGER PRIMARY KEY, eId INTEGER REFERENCES e(id));
        INSERT INTO b (id) VALUES (1);
        INSERT INTO a (id, bId) VALUES (1, 1);
        INSERT INTO c (id, bId) VALUES (1, 1);
        INSERT INTO d (id, cId) VALUES (1, 1);
        INSERT INTO e (id, bId) VALUES (1, 1);
        INSERT INTO f (id, eId) VALUES (1, 1);
        """)
    _ = try A.including(
        required: A.b
            .including(
                optional: B.c
                    .including(all: C.ds)
            )
            .including(
                optional: B.e
                    .including(all: E.fs)
            )
    )
    .fetchAll(db)
}
```

</details>

**Comment by noefroidevaux** [comment] 2023-01-12 08:54
> Hello @noefroidevaux, thanks for the compliment :-)
> 
> It looks like you found a bug indeed, thank you very much 👍
> 
> There is no known workaround :-/
> 
> Please hold on until the fix ships! Just in case, did you happen to investigate?
> 
> Reproducing code

Hello @groue 

Thank you for your fast answer!

No, I haven't done any investigation in the library as I didn't know if it was a bug or a deliberate/known limitation. When I have a moment, I'll try and post here if I see anything relevant.

**Comment by groue** [comment] 2023-01-12 09:03
> When I have a moment, I'll take a look and post here if I see anything relevant.

I've started looking a bit. I'm afraid the problem occurs in a difficult area of GRDB! You really don't have to investigate, and you can rest until I ship a fix. If you still want to have a look, don't expect to be fast 😅

**Comment by noefroidevaux** [comment] 2023-01-12 09:09
> I've started looking a bit. I'm afraid the problem occurs in a difficult area of GRDB! You really don't have to investigate, and you can rest until I ship a fix. If you still want to have a look, don't expect to be fast 😅

Ok, thanks for the warning 😄👍

**Comment by groue** [comment] 2023-01-15 14:12
Fixed with #1317. I'm preparing the next release.

**Comment by groue** [comment] 2023-01-15 14:32
Shipped in v6.6.1. Thank you again for the report, @noefroidevaux 👍

**Closed by groue** 2023-01-15 14:32 UTC
Labels: bug

**Comment by noefroidevaux** [comment] 2023-01-17 09:50
Hello @groue ,

I have tested in my application and it seems all ok! A big thank you for the fix!!! 😃

**Comment by groue** [comment] 2023-01-17 11:03
😊 Thank you for sponsoring the project 💝
