### ISSUE TITLE
Async/await causing crash when running on pre iOS/tvOS 13 devices

### ISSUE THREAD

**Issue by gabors** [groue/GRDB.swift#1134] opened 2022-01-12 04:00 UTC
Hi @groue 

I'm integrating GRDB via SPM.
I ran into the issue of my apps now crashing on devices with iOS/tvOS 12 and older.
This is because GRDB versions after 5.16 introduced support for async/await which unfortunately pulls in the  libswift_Concurrency.dylib that makes the app crash on those devices.

```
Exception Type:  EXC_CRASH (SIGABRT)
Exception Codes: 0x0000000000000000, 0x0000000000000000
Exception Note:  EXC_CORPSE_NOTIFY
Termination Description: DYLD, Symbol not found: ___chkstk_darwin | Referenced from: /private/var/containers/Bundle/Application/4A0BA4F4-9C79-4A22-8067-5CB63B419A74/FYC.app/Frameworks/libswift_Concurrency.dylib (which was built for iOS 13.0) | Expected in: dyld shared cache | in /private/var/containers/Bundle/Application/4A0BA4F4-9C79-4A22-8067-5CB63B419A74/FYC.app/Frameworks/libswift_Concurrency.dylib
```

I ran into this problem with a different framework on iOS 12
Alamofire/Alamofire#3529

This unfortunately prevents us from taking advantage of the great improvements in GRDB 5.17 and 5.18.
Anyway, I thought you should know since your wonderful library supports those older OS versions.

**Comment by groue** [comment] 2022-01-12 06:00
Hello @gabors,

This is a duplicate of #1123 (I'll pin it).

> your wonderful library supports those older OS versions

Thanks for telling this. The introduction of async/await has been, practically speaking, a (surprise!) breaking change. I still have a hope that Apple fixes this, but when it is clear for everybody that they won't, I'll update the library requirements.

Meanwhile, GRDB 5.16.0 is the last version that currently supports iOS/tvOS < 13.

**Closed by groue** 2022-01-12 06:00 UTC

**Comment by gabors** [comment] 2022-01-12 06:28
Perhaps you can update the SupportedPlatform values on the newer versions to minimum 13? Is that possible?

**Comment by groue** [comment] 2022-01-12 06:34
I'm sorry I do not get it. At which place? What would it change for you?

**Comment by gabors** [comment] 2022-01-12 06:36
> I'm sorry I do not get it. At which place? What would it change for you?

I was thinking about this if it makes sense. 

https://developer.apple.com/documentation/swift_packages/supportedplatform

**Comment by groue** [comment] 2022-01-12 06:40
As I said above:

> I still have a hope that Apple fixes this, but when it is clear for everybody that they won't, I'll update the library requirements.

if this "wait and see" stance creates a problem, please explain.

**Comment by gabors** [comment] 2022-01-12 06:45
> As I said above:
> 
> 
> 
> > I still have a hope that Apple fixes this, but when it is clear for everybody that they won't, I'll update the library requirements.
> 
> 
> 
> if this "wait and see" stance creates a problem, please explain.

Well as it stands now if someone uses the current GRDB version in an app that supports OS below version 13 their app will crash on those older versions. 
Apple may fix this of course but we don't know when. 
So it seems reasonable at this time for GRDB to require min OS version 13.

**Comment by groue** [comment] 2022-01-12 06:56
I won't do this now. And I do not thank Apple for the churn their lack of basic testing is creating.

**Comment by groue** [comment] 2022-01-12 06:57
You can help, though, by reporting the issue at https://feedbackassistant.apple.com/

**Comment by gabors** [comment] 2022-01-12 07:40
> I won't do this now. And I do not thank Apple for the churn created by their lack of testing.

It's up to you of course. 
At least please add some info to the readme. So other devs can avoid their apps crashing. 

Yes it's been a mess that apple created. This is the third framework I ran into with my apps. I missed the async await commit in grdb and pushed a version to the AppStore that now crashes on iOS 11 and 12. 
TestFlight no longer works below 13 so it's not even possible to test for this easily.

**Comment by groue** [comment] 2022-01-12 08:10
Yes, I'm deeply sorry.

The README update won't be noticed by people who just upgrade, so I doubt its effectiveness at preventing many people from feeling your pain.

Do report a bug at Apple.

Do check https://forums.swift.org/t/swift-concurrency-back-deploy-issue/53917 for updates

**Comment by serges147** [comment] 2022-01-13 06:17
BTW, the same story for macOS 10.12 & 10.13 (probably 10.14 as well). On 10.15+ it works. And 5.16.0 helps.
