### ISSUE TITLE
grdb does not build on xcode 8 (swift version 2.3)

### ISSUE THREAD

**Issue by mtissington** [groue/GRDB.swift#112] opened 2016-09-08 17:55 UTC
The following file needs to be changed

NSURL.swift (note the addition of the bang)

    public var databaseValue: DatabaseValue {
        return absoluteString!.databaseValue
    }

**Comment by groue** [comment] 2016-09-08 20:38
Hello @mtissington 

I don't plan at all supporting Swift 2.3, for I don't expect the Swift 2.3 need to last more than a few weeks, and don't have the time to support both Swift 2.3 and Swift 3. Maintaining GRDB on many platforms and variants (SQLCipher + custom SQLite build) is time-consuming, that's a dull but hard fact. Future developments will only happen on Swift 3.

Will you be able to hold on until you migrate to Swift3 (which I hope you do eventually) ?

**Comment by groue** [comment] 2016-09-08 20:39
I'm closing this issue as a duplicate of #110

**Closed by groue** 2016-09-08 20:39 UTC

**Comment by mtissington** [comment] 2016-09-08 21:23
I'd switch to 3 now if all the pods supported 3 but they don't and I doubt they are as quick off the mark as you..

I hope I'm wrong but I think you might need to support 2.3 for a few months.
The current fix I mentioned is trivial. At least then .80 will work.

Michael

**Comment by groue** [comment] 2016-09-09 05:06
You and @dral3x are starting to make me fear that Apple has trapped itself in a Python2 / Python3 nightmare.

**Comment by groue** [comment] 2016-09-09 07:04
OK @mtissington, @dral3x - I'll release a Swift 2.3 version. I've looked at major Swift libs, and they do provide support for this version of the language as an upgrade path - sorry for my delay realizing this.

Please check the top of the [README](https://github.com/groue/GRDB.swift) for details and current state of affairs.

**Comment by groue** [comment] 2016-09-10 11:32
There we go: version 0.81.0 is out, with Swift 2.3 support.
