### ISSUE TITLE
Strange behavior after normal installation with CocoaPods

### ISSUE THREAD

**Issue by robertocalvi** [groue/GRDB.swift#152] opened 2016-12-08 22:50 UTC
Building an empty projectGRDB.swift Gave me two issues:
==============Swift compiler ERROR 1=============
`/Applications/Xcode.app/Contents/Developer/Platforms/WatchSimulator.platform/Developer/SDKs/WatchSimulator.sdk/usr/include/sqlite3.h:35:2: Module 'Darwin' was built in directory '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator10.1.sdk/usr/include' but now resides in directory '/Applications/Xcode.app/Contents/Developer/Platforms/WatchSimulator.platform/Developer/SDKs/WatchSimulator.sdk/usr/include'`
sqlite3.h

==============Swift compiler ERROR 2=============
`/Users/roberto/Documents/XCODE/GRDB/Recipes-2015/Pods/GRDB.swift/GRDB/Core/Configuration.swift:8:20: Could not build Objective-C module 'SQLiteiPhoneSimulator'`
Configuration.swift

Could you please help me?
Thanks Rob

**Comment by groue** [comment] 2016-12-09 05:13
Hello Roberto.

I can't reproduce your issue, and use GRDB with CocoaPods without any trouble. Did you follow the [instructions](https://github.com/groue/GRDB.swift#cocoapods)?

**Comment by robertocalvi** [comment] 2016-12-09 17:00
Hello Gwendal,
Yes i followed all the instuction many times, perhaps because l'm using Xcode 8.1+ • Swift 3.0.1?

**Comment by groue** [comment] 2016-12-09 17:17
@robertocalvi, Xcode 8.1 is a perfect fit.

The `Could not build Objective-C module 'SQLiteiPhoneSimulator'` error may happen from time to time, and is generally solved by a clean rebuild of the project, and is not your interesting error. (To perform a clean rebuild of the project, hold the Alt key and choose menu Product > Clean Build Folder).

Your interesting error is the `Module 'Darwin' was built in directory … iPhoneSimulator10.1 … but now resides in directory … WatchSimulator.sdk` error, because it contains both "iPhone" and "Watch" in the same sentence. Did you investigate this?

**Comment by singhnitesh** [comment] 2016-12-13 07:19
Hi, I am also getting the same error (along with few more). Using Xcode 8.1, Swift 3.0.1, Cocoapods 1.1.1. Any leads?
![screen shot 2016-12-13 at 12 33 37 pm](https://cloud.githubusercontent.com/assets/1753710/21131034/5ee06a7a-c132-11e6-8393-3c59d78b2fce.png)

**Comment by groue** [comment] 2016-12-13 07:29
@singhnitesh I can't reproduce your issue, so no, I can't help. Clean everything. Check for conflict with other pods. Isolate the origin of the problem by creating an empty project in which you add elements one after the other until you get an error. Investigate.

**Comment by singhnitesh** [comment] 2016-12-13 08:16
I was using two xcodes, Xcode7.3 was in Applications, while Xcode8.1 was in Downloads, after replacing Xcode7 with Xcode8 all the errors disappeared.

**Comment by groue** [comment] 2016-12-13 08:18
Great, @singhnitesh! And thanks for telling us. Maybe this will help @robertocalvi.

**Comment by groue** [comment] 2016-12-15 11:28
No news, closing.

**Closed** 2016-12-15 11:28 UTC
Labels: invalid

**Comment by Kirow** [comment] 2017-06-03 14:25
Had same problem. tried to make clean, update CLI, reinstall xcode, reboot - nothing helped.
Reinstall pods - and error dissapeared (should try it after clean)
