### ISSUE TITLE
Reusing a database with costly migrations

### ISSUE THREAD

**Issue by anlaital-oura** [groue/GRDB.swift#1563] opened 2024-06-27 06:49 UTC
### What did you do?

We have databases that have **a lot** of migrations. Running the migrations takes ~400ms on an M2 Max for each database. This is a problem in unit tests because these migrations for each database get run almost two thousand times, making the tests sluggish.

### What did you expect to happen?

I would like to be able to run the costly migrations once and then use the newly migrated database as a clean slate for each test case. However, I couldn't figure out a good and performant way to do this with GRDB. 

### What happened instead?

N/A

### Environment

**GRDB flavor(s):** GRDB
**GRDB version:** 6.27.0
**Installation method:** SPM
**Xcode version:** 15.4
**Swift version:** 5.10
**Platform(s) running GRDB:** iOS
**macOS version running Xcode:** 14.5

### Demo Project

N/A

**Comment by groue** [comment] 2024-06-27 07:12
Hello, @anlaital-oura,

Please check the [Foreign Key Checks](https://swiftpackageindex.com/groue/grdb.swift/documentation/grdb/migrations#Foreign-Key-Checks) section of the migrations documentation.

It explains the reason why migrations can take time, and gives some mitigations techniques.

Take care that the mitigation techniques requires some care, because the application becomes responsible for the integrity of its database. Please ask a question if the documentation leaves some unanswered question.

**Comment by groue** [comment] 2024-06-27 07:30
Oops, I missed this other sentence of yours:

> I would like to be able to run the costly migrations once and then use the newly migrated database as a clean slate for each test case. However, I couldn't figure out a good and performant way to do this with GRDB.

One technique you could use is to:

1. Each test looks for a database at some location on disk. If it does not exist, it creates an empty database. In all cases, it migrates it with the [`eraseDatabaseOnSchemaChange`](https://swiftpackageindex.com/groue/grdb.swift/v6.27.0/documentation/grdb/databasemigrator/erasedatabaseonschemachange) option.

    This database is the template for other tests.

    Take care that this setup must not run in parallel from multiple tests, including tests that run from multiple processes, so you probably need to use a `NSFileCoordinator` or another file-system-level synchronization technique.

    The template database should probably not be committed in your git repo. Thanks to the `eraseDatabaseOnSchemaChange` options, you shouldn't have to delete it whenever you modify a migration during development.

2. Now each test should work on a private copy of the template database, so that the test can not alter the behavior of other tests. You have multiple options for copying databases.

    If your tests can run with a `DatabaseQueue`, you will enjoy one of those:

    - [`DatabaseQueue.inMemoryCopy(fromPath:configuration:)`](https://swiftpackageindex.com/groue/grdb.swift/v6.27.0/documentation/grdb/databasequeue/inmemorycopy(frompath:configuration:))
    - [`DatabaseQueue.temporaryCopy(fromPath:configuration:)`](https://swiftpackageindex.com/groue/grdb.swift/v6.27.0/documentation/grdb/databasequeue/temporarycopy(frompath:configuration:))
    
    If your tests require a `DatabasePool`, then any database copy technique will work: [`vacuum(into:)`](https://swiftpackageindex.com/groue/grdb.swift/v6.27.0/documentation/grdb/databasewriter/vacuum(into:)-5lo41), or [`backup(to:)`](https://swiftpackageindex.com/groue/grdb.swift/v6.27.0/documentation/grdb/databasereader/backup(to:pagesperstep:progress:)).

**Comment by groue** [comment] 2024-06-27 07:39
> I noticed that if I have an in-memory database that is migrated and when I call `backup(to:)` on it to another clean database (without any migrations in the new database), then the migrations are not copied. I assume it only copies data and not the empty table definitions resulting from the migrations themselves, meaning that the database that is being copied to must also have compatible schema defined already?

I'm not sure I understand, because an [SQLite backup](https://www.sqlite.org/backup.html) performs a full copy, replacing any original contents of the target database. In particular, SQLite backup is not aware of GRDB migrations, so they are copied with everything else.

**Comment by groue** [comment] 2024-06-27 07:42
> Hmm, this is very strange then indeed! I implemented the `backup(to:)` approach earlier and in subsequent tests I started getting an error about tables not existing in the newly-minted backup. I can investigate this further if indeed `backup(to:)` should also copy the full schema, including migrations and the (empty) tables that are created as a result of those migrations.

Yes. Something is fishy here. I wouldn't expect SQLite backup to be buggy, so maybe you found a GRDB bug, or there is a bug in your tests. Please report the results of your investigations when you have time! 👍

**Comment by groue** [comment] 2024-06-27 07:45
OK @anlaital-oura, so it looks like the topic of the issue is shifting 🙂 Maybe share the technique used by the failing tests?

**Closed as completed** 2024-06-27 08:04 UTC
Labels: support

**Comment by groue** [comment] 2024-06-27 08:08
That's much better indeed! Thank you @anlaital-oura for sharing this experience and exploration 👍 Happy GRDB!
