### ISSUE TITLE
disk I/O error in "PRAGMA foreign_key_check"

### ISSUE THREAD

**Issue by nrkrishna** [groue/GRDB.swift#1097] opened 2021-11-17 02:24 UTC
When attempting to initialize/use an existing database pool in an iOS app, it sometimes fails with the error "Unresolved error SQLite error 10: disk I/O error - while executing `PRAGMA foreign_key_check`".

This is happening when I try to run my app in XCode. I suspect this is also happening in the wild as I'm getting crashlytics reports for failure in the makeShared() function below. Rerunning the app in debug mode seems to initialize the database correctly. So something is certainly up in that randomly it fails with the above fatal error. 

I got the following console logs just before the fatal error:

> 2021-11-16 21:06:57.136183-0500 App[80317:8104297] [logging] BUG IN CLIENT OF libsqlite3.dylib: database integrity compromised by API violation: vnode unlinked while in use: /private/var/mobile/Containers/Data/Application/B9790B45-FD81-4DC7-9E33-BBCF15F471EE/tmp/C5C899F1-4312-4268-B645-EC9EBCD8B8FF-80317-000010EC6B40026C
2021-11-16 21:06:57.136250-0500 App[80317:8104297] [logging] invalidated open fd: 25 (0x11)
2021-11-16 21:06:57.136495-0500 App[80317:8104037] [logging] disk I/O error in "PRAGMA foreign_key_check"
2021-11-16 21:06:57.136784-0500 App[80317:8104037] [logging] disk I/O error in "PRAGMA foreign_keys = ON"

The code to initialize the database is as follows:

OFLocalDatabase is just a wrapper around DatabaseWriter. 

Init method for OFLocalDatabase is also provided below. 

`

private static func makeShared() -> OFLocalDatabase {
        guard let baseDir = FileManager().containerURL(forSecurityApplicationGroupIdentifier:"group.com.something.something") else {
            fatalError("Unresolved error - group identifier container folder dfoesn't exist")
        }
        
        do {
            // Create a folder for storing the SQLite database, as well as
            // the various temporary files created during normal database
            // operations (https://sqlite.org/tempfiles.html).
            
            let folderURL = baseDir.appendingPathComponent("database", isDirectory: true)
            try FileManager().createDirectory(at: folderURL, withIntermediateDirectories: true)
            
            // Connect to a database on disk
            // See https://github.com/groue/GRDB.swift/blob/master/README.md#database-connections
            let dbURL = folderURL.appendingPathComponent("db.sqlite")
            let dbPool = try DatabasePool(path: dbURL.path)
            
            // Create the AppDatabase
            let appDatabase = try OFLocalDatabase(dbPool)
            
            return appDatabase
        } catch {
            // Replace this implementation with code to handle the error appropriately.
            // fatalError() causes the application to generate a crash log and terminate.
            //
            // Typical reasons for an error here include:
            // * The parent directory cannot be created, or disallows writing.
            // * The database is not accessible, due to permissions or data protection when the device is locked.
            // * The device is out of space.
            // * The database could not be migrated to its latest schema version.
            // Check the error message to determine what the actual problem was.
            fatalError("Unresolved error \(error)")
        }
    }
    
    /// Creates an `AppDatabase`, and make sure the database schema is ready.
    init(_ dbWriter: DatabaseWriter) throws {
        self.dbWriter = dbWriter
        try migrator.migrate(dbWriter)
    }`

Let me know if providing any additional code from this class will be helpful. 

### Environment

**GRDB version:5.11.0**
**Installation method:Manual** 
**Xcode version:13.1**
**Swift version:5**
**Platform(s) running GRDB:iPad OS 15.0.2**

**Comment by groue** [comment] 2021-11-17 07:25
Hello @nrkrishna,

The source of the problem is likely this line in the log:

```
BUG IN CLIENT OF libsqlite3.dylib: database integrity compromised by API violation: vnode unlinked while in use
```

"vnode unlinked" means "file deleted". Something deletes the database file, preventing the database operations from completing successfully. This something is in your app: locate it, and you'll fix this error.

**Comment by nrkrishna** [comment] 2021-11-17 14:18
@groue thanks for the quick reply. I'm not sure what would cause that but thanks for the helpful pointer. Do you think that could be because I'm running the app in the debugger? I know the debugger moves project directories around in a way that I don't fully understand.

**Comment by groue** [comment] 2021-11-17 14:44
I'm sorry @nrkrishna, I don't know who is deleting your database files, or the folder that contains it. I know it is not GRDB. And I never heard of a debugger or simulator that would delete files either.

BTW, I see that you use `FileManager().containerURL(forSecurityApplicationGroupIdentifier:)`, so you store your database in a shared container. Make sure you check what other apps in the group do, too.

One last thing…

**In a shared container, your simple way to open the database is no longer suitable.**

Storing an SQLite database in a shared container is 💥 **HARD** 💀, so there is a dedicated guide about it: [Sharing a database](https://github.com/groue/GRDB.swift/blob/master/Documentation/SharingADatabase.md). Don't miss it, even if it is a difficult read. If you can avoid storing your database in a shared container, this will be _much easier_.

**Comment by nrkrishna** [comment] 2021-11-17 15:22
Got it @groue. I'll try and chase this thing down. Yes, I did read the referenced article about sharing a database. Luckily its used by a sharing extension and they operate in a mutually exclusive manner almost always. I'll close this for now. Appreciate all the amazing work you are doing and the excellent support you are providing.

**Comment by nrkrishna** [comment] 2021-11-22 14:42
@groue I think I identified the issue. I had `eraseDatabaseOnSchemaChange` enabled in DEBUG mode. What's odd is that as per the documentation, a database erase should only happen if the following conditions are true. No migrations were removed or renamed since these are just successive runs off the same code while troubleshooting a non-db related issue. I can't say intelligently if a scheme change happened under the hoods or not. 

Upon commenting out the `eraseDatabaseOnSchemaChange` flag, it runs without crashing as noted above. Any clues/tips on what I should be looking for? Thanks

From https://github.com/groue/GRDB.swift/blob/master/Documentation/Migrations.md#the-erasedatabaseonschemachange-option:

_A migration has been removed, or renamed.
A schema change is detected. A schema change is any difference in the sqlite_master table, which contains the SQL used to create database tables, indexes, triggers, and views._

**Comment by groue** [comment] 2021-11-22 14:54
Hello again @nrkrishna. That's... interesting. Do you have a reproducing case, please? I mean the code for a migrator that reproduces the issue.

**Comment by groue** [comment] 2021-11-22 14:57
Also... If two migrators run _at the same time_, from different threads or processes, then _of course_ `eraseDatabaseOnSchemaChange` will create problem. It is the responsibility of the application to prevent two migrators from running concurrently, with `NSFileCoordinator`, as documented in [Sharing a Database](https://github.com/groue/GRDB.swift/blob/master/Documentation/SharingADatabase.md).

**Comment by nrkrishna** [comment] 2021-11-22 15:11
@groue I put it behind a singleton and so its unlikely two different threads are accessing it at the same time BUT let me test that theory as I'm not sure what would happen if the migrate method (see below) takes a long time to return and another thread is trying to access the singleton object at the same time. I'll get back to you on that. But why would it erase the DB seeing there are no db changes? 

I do have it reproducing but its in my main project. I'll see if I can spawn it off into a separate project if my above investigation doesn't go anywhere. 

See code below:

`final class OFLocalDatabase {
    
    static let shared = makeShared()
    
    /// Creates an `AppDatabase`, and make sure the database schema is ready.
    init(_ dbWriter: DatabaseWriter) throws {
        self.dbWriter = dbWriter
        try migrator.migrate(dbWriter)
    }

    private var migrator: DatabaseMigrator {
        var migrator = DatabaseMigrator()
        
        #if DEBUG
        // Speed up development by nuking the database when migrations change
        // See https://github.com/groue/GRDB.swift/blob/master/Documentation/Migrations.md#the-erasedatabaseonschemachange-option
        //migrator.eraseDatabaseOnSchemaChange = true
        #endif
        
        migrator.registerMigration("createTable") { db in
            // Create a table
            // See https://github.com/groue/GRDB.swift#create-tables
            try db.create(table: "video") { t in
                t.column("id", .text).primaryKey()
                t.column("column1", .text).notNull()
                t.column("column2", .date).notNull()
...
`

**Comment by groue** [comment] 2021-11-22 15:14
> See code below:

This is not a reproducing case.

> But why would it erase the DB seeing there are no db changes?

You tell me. Running two migrators concurrently is not a normal setup, so here be dragons.

> I suspect this is also happening in the wild as I'm getting crashlytics reports for failure in the makeShared() function below.

I'm surprised you get errors in production that may be related to `eraseDatabaseOnSchemaChange`, because it is [not recommended](https://github.com/groue/GRDB.swift/blob/master/Documentation/Migrations.md#the-erasedatabaseonschemachange-option) to ship this flag in production. It is a destructive flag, so something that is _very dangerous_ for your users' data.

You can ship it, of course. But if your goal is just to speed up development when the schema is still in flux, and you don't want to risk a catastrophic erasure of user data, then the recommended setup is:

```swift
var migrator = DatabaseMigrator()
#if DEBUG
// Speed up development by nuking the database when migrations change
migrator.eraseDatabaseOnSchemaChange = true
#endif
```

**Comment by nrkrishna** [comment] 2021-11-22 15:17
I confirmed the production issue was because those users were running out of space on their device. So the production issue is unrelated. 

I'm fairly certain two migrators are not running concurrently but you know what I've been proven wrong 100s of times in the past, so let me double triple confirm that. I'll report back.

**Comment by groue** [comment] 2021-11-22 15:21
All right, @nrkrishna. I'm patient, and I will fix the GRDB bug if we find one 👍

**Comment by groue** [comment] 2021-12-03 11:59
Any news, @nrkrishna? I'm patient, but I also do not like keeping issues open when nobody works on it ;-)

**Comment by groue** [comment] 2021-12-07 14:17
No news is good news: I'm closing this issue. Feel free to reopen if you find something wrong in GRDB!

**Closed by groue** 2021-12-07 14:17 UTC
Labels: support
