### ISSUE TITLE
 'sqlite3_trace' is deprecated

### ISSUE THREAD

**Issue by axgle** [groue/GRDB.swift#127] opened 2016-09-25 02:09 UTC
Swift Compiler Warning Group(swift 3)
/Users/username/github/GRDB.swift/GRDB/Core/Database.swift:291:9: 'sqlite3_trace' is deprecated

**Comment by groue** [comment] 2016-09-25 02:30
Duplicate of #100

**Closed by groue** 2016-09-25 02:30 UTC
Labels: invalid
