### ISSUE TITLE
Xcode 12.4 crashing after adding package 

### ISSUE THREAD

**Issue by tcoates1970** [groue/GRDB.swift#1176] opened 2022-02-20 07:01 UTC
### What did you do?

using the swift package manager I added the GRDB package. I did NOT select the dynamic version to use.

### What did you expect to happen?

package is added and I can continue to work on project

### What happened instead?

after about 10-15 seconds xcode crashes with error message as shown at the end of this post.

### Environment

**GRDB flavor(s):** GRDB
**GRDB version:**
**Installation method:** swift package manager
**Xcode version:** 12.4
**Swift version:**
**Platform(s) running GRDB:** iOS
**macOS version running Xcode:** Catalina 10.15.7

### Demo Project

The following information is displayed when xcode crashes...

```
Process:               Xcode [18785]
Path:                  /Applications/Xcode.app/Contents/MacOS/Xcode
Identifier:            com.apple.dt.Xcode
Version:               12.4 (17801)
Build Info:            IDEFrameworks-17801000000000000~7 (12D4e)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           Xcode [18785]
User ID:               715

Date/Time:             2022-02-20 14:53:46.593 +0800
OS Version:            Mac OS X 10.15.7 (19H1615)
Report Version:        12
Anonymous UUID:        DDC15F64-2500-A409-F2B2-9978B952B30C

Time Awake Since Boot: 43000 seconds

System Integrity Protection: disabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_INSTRUCTION (SIGILL)
Exception Codes:       0x0000000000000001, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Illegal instruction: 4
Termination Reason:    Namespace SIGNAL, Code 0x4
Terminating Process:   exc handler [18785]

Application Specific Information:
ProductBuildVersion: 12D4e

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   com.apple.dt.IDESwiftPackageCore	0x000000012ef7682b PIF.Project.addTarget(id:productType:name:productName:) + 1211
1   com.apple.dt.IDESwiftPackageCore	0x000000012ef54690 specialized constructLibraryProductBlueprint #1 (_:type:productIdSuffix:embedResources:) in PackagePIFBuilder.build() + 688
2   com.apple.dt.IDESwiftPackageCore	0x000000012ef40ce6 PackagePIFBuilder.build() + 11286
3   com.apple.dt.IDESwiftPackageCore	0x000000012ef67dcf IDESwiftPackage.update(from:) + 2687
4   com.apple.dt.IDESwiftPackageCore	0x000000012ef35365 IDESPMWorkspaceDelegate.dependencyPackageDidUpdate(package:) + 1461
5   com.apple.dt.SwiftPM          	0x000000012f0719c0 closure #10 in closure #1 in SPMWorkspace.processPackageGraphActionsInBackgroundIfNeeded() + 3360
6   com.apple.dt.SwiftPM          	0x000000012f0806e1 partial apply for thunk for @callee_guaranteed () -> () + 17
7   com.apple.dt.SwiftPM          	0x000000012f074bfe thunk for @escaping @callee_guaranteed () -> () + 14
8   libdispatch.dylib             	0x00007fff6c81c658 _dispatch_client_callout + 8
9   libdispatch.dylib             	0x00007fff6c8287ab _dispatch_async_and_wait_invoke + 87
10  libdispatch.dylib             	0x00007fff6c81c658 _dispatch_client_callout + 8
11  libdispatch.dylib             	0x00007fff6c827cab _dispatch_main_queue_callback_4CF + 936
12  com.apple.CoreFoundation      	0x00007fff32a62493 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
13  com.apple.CoreFoundation      	0x00007fff32a2210a __CFRunLoopRun + 2042
14  com.apple.CoreFoundation      	0x00007fff32a212b3 CFRunLoopRunSpecific + 466
15  com.apple.HIToolbox           	0x00007fff3163caad RunCurrentEventLoopInMode + 292
16  com.apple.HIToolbox           	0x00007fff3163c7c5 ReceiveNextEventCommon + 584
17  com.apple.HIToolbox           	0x00007fff3163c569 _BlockUntilNextEventMatchingListInModeWithFilter + 64
18  com.apple.AppKit              	0x00007fff2fc85659 _DPSNextEvent + 883
19  com.apple.AppKit              	0x00007fff2fc83ea0 -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1352
20  com.apple.dt.DVTKit           	0x0000000102734d07 -[DVTApplication nextEventMatchingMask:untilDate:inMode:dequeue:] + 421
21  com.apple.AppKit              	0x00007fff2fc75bae -[NSApplication run] + 658
22  com.apple.AppKit              	0x00007fff2fc47996 NSApplicationMain + 777
23  libdyld.dylib                 	0x00007fff6c875cc9 start + 1

Th
```

**Comment by freak4pc** [comment] 2022-02-20 13:35
This doesn't seem GRDB-specific though, rights? The crash is in Xcode itself.
A good first step would be trying to use a regular Package.swift file and see if the problem persists. Updating your Xcode will probably solve it, too.

**Comment by groue** [comment] 2022-02-22 10:04
Hello @tcoates1970,

I can reproduce your issue. When I setup an iOS app project with a SPM dependency on GRDB with Xcode 12.4, Xcode crashes before the GRDB package is fully installed, with the same stack trace as yours.

That's unfortunate, because Xcode 12.4 is supposedly still supported. Unfortunately, it is difficult to automatically test many versions of Xcode, and I don't quite know when it has started crashing.

Are you really stuck with this version of Xcode? If so, did you try to bisect GRDB versions until you find one that starts to trigger this crash?

**Comment by groue** [comment] 2022-02-27 17:06
@tcoates1970, any news?

**Comment by groue** [comment] 2022-02-28 09:13
> did you try to bisect GRDB versions until you find one that starts to trigger this crash?

I flag the issue with the "help wanted" tag: contributions are welcome!

**Comment by groue** [comment] 2022-03-22 14:04
@tcoates1970, no news is good news: I'm closing this issue. Meanwhile, https://developer.apple.com/forums/thread/660678 can provide some help.

**Closed by groue** 2022-03-22 14:04 UTC
Labels: help wanted
