### ISSUE TITLE
async/await crashing debug build

### ISSUE THREAD

**Issue by suau** [groue/GRDB.swift#1198] opened 2022-03-31 12:08 UTC
I upgraded GRDB to 5.22.1
which seemed to work fine,
but it crashes on startup under these very specific circumstances:
- physical test device is on iOS 14.4.2 (probably any device iOS <15)
- running debug build installed via XCode
- and debugger is not attached

it does NOT seem to cause an issue if:
- installed and run using XCode (debugger is attached)
- running on a simulator, 14.4, 14.5 and 15.2 both work
- release build downloaded from AppStore (bitcode is enabled)

Checking the device console I saw this error, which displayed
`Unable to create process info for pid ... task ... Is dyld loaded for this binary yet?`
and led me to several issues related to swift concurrency with async/await and XCode / bitcode.

downgrading to 5.16 solves the issue.
But I'm left confused with a few questions:
- I have already released a version with 5.22.1 and bitcode enabled to the AppStore, it seems to work fine and I'm not sure if I need to release a fix or not. Does the release build / archiving process strip the offending code since I'm not using async/await ?
- Why does the debug build work if the debugger is attached ? As far as I understand the underlying library is simply not present before iOS 15 ? What difference does the debugger make ?
- Why does it work on a iOS 14.4 simulator ? Is the simulator not completely sandboxed and should use the same swift version as a physical iOS 14.4 device ?
- This issue as per #1185 seems to cause even more issues when using XCode 13.3, should async/await maybe moved into it's own version of GRDB (v6?) leaving v5 for iOS 11-14 ?

GRDB 5.17 - 5.22.1 via CocoaPods
XCode 13.2.1
Swift 5.5
iOS (14.3+)
XCode running on macOS 12.1

**Comment by groue** [comment] 2022-03-31 12:14
Hello @suau, it looks like a duplicate of #1185 indeed.

> should async/await maybe moved into it's own version of GRDB (v6?) leaving v5 for iOS 11-14 ?

This is not the current plan (see the #1185 conversation for more information).

**Comment by groue** [comment] 2022-03-31 12:25
> But I'm left confused with a few questions

I'm just as confused as your are. Maybe other users will have a better understanding.

**Comment by groue** [comment] 2022-04-02 13:11
Closing because I'm not sure there's much to add. #1185 is already pinned.

**Closed by groue** 2022-04-02 13:11 UTC
Labels: wontfix

**Comment by suau** [comment] 2022-04-06 10:48
Just to keep everyone updated.
Issues range from
- unable to upload when bitcode is enabled
- crash in the production build
- crash only in the debug build

I only encountered issues with the debug build and after monitoring it for a week it seems the production build does not cause any issues.
