### ISSUE TITLE
Deadlock in Pool.swift in v6.10.1

### ISSUE THREAD

**Issue by mattgallagher** [groue/GRDB.swift#1362] opened 2023-04-12 06:48 UTC
Since updating to 6.10, I've been seeing deadlocks with threads stuck at `itemsSemaphore.wait()` at Pool.swift line 80. The stack traces themselves aren't hugely informative but I have a suspicion that something in v6.10 has lead to unbalanced calls to `itemsSemaphore.signal()` – possibly https://github.com/groue/GRDB.swift/pull/1350.

![Screenshot 2023-04-12 at 16 47 42](https://user-images.githubusercontent.com/28080/231374170-eba9413d-db04-4142-a9ac-e2be429cb51d.png)

**Comment by groue** [comment] 2023-04-12 06:56
Hello @mattgallagher,

Yes, #1350 is certainly the origin of the regression, I'm sorry 😕. Is it possible for you to downgrade to v6.9.2 until the deadlock is understood and fixed?

A possible explanation is that the internal `WALSnapshotTransaction` class "forgets" to call its `release` closure - because the class contains a logic bug, or because an instance is leaked. Please hold on.

**Comment by mattgallagher** [comment] 2023-04-12 06:57
Yes, we've already reverted (and never shipped 6.10).

**Comment by groue** [comment] 2023-04-12 06:57
Phew

**Comment by mattgallagher** [comment] 2023-04-13 07:51
I'll take a closer look. The scenario we have is where 1 table with approximately 20 observers is written. The readers all finish but subsequent writes get blocked.

I might need to run an editable checkout of GRDB and instrument the itemsSemaphore to see what's happening.

**Comment by groue** [comment] 2023-04-13 15:15
> In your memory, was it a real dead-lock? I mean, could it have been reader starvation?

I can describe how #1350 has enabled a new scenario for reader starvation. First imagine there's a long-running background write transaction. For example, your app is synchronizing a big server payload. Meanwhile, your app starts a lot of observations. The first ones grab a reader connection. But they won't release it until they can acquire a write access, until the long-running write transaction has completed. Only then they'll register as transaction observers and start actual observation. Eventually all readers are taken, waiting for the completion of the long-running write transaction. Subsequent observations will thus be enqueued. They won't be able to perform their initial fetch. They will just look as if they were stuck in a deadlock. But they are only stuck temporarily - that's what I could test in various observation scenarios.

I do not know if this is what your application is suffering from, to be clear.

Before #1350, #1248 has started opening a new connection whenever an observation would start.

This was cool, but `maximumReaderCount` was ignored. And SQLCipher can be [very slow](https://github.com/groue/GRDB.swift/issues/1256#issuecomment-1471438995) when it opens a new connection. And generally I have realized that people can perform anything in their database setup, including very slow stuff, so it's really not a good idea to open new connections lightly.

That's why #1350 has started enforcing the [`maximumReaderCount`](https://swiftpackageindex.com/groue/grdb.swift/v6.10.2/documentation/grdb/configuration/maximumreadercount) configuration flag.

That was all supposed to be for the better.

I'm well aware of the [Hyrum's Law](https://www.hyrumslaw.com/), so maybe your app has started relying of the generous behavior of #1248 - this is something I'm open to discuss.

But first we need to know what's has happened to your app :-)

**Comment by groue** [comment] 2023-04-14 10:25
🎉 Maybe we're on to something, because my "aggressive" tests fail in CI: https://github.com/groue/GRDB.swift/actions/runs/4697040628

**Comment by groue** [comment] 2023-04-15 09:26
> 🎉 Maybe we're on to something, because my "aggressive" tests fail in CI: https://github.com/groue/GRDB.swift/actions/runs/4697040628

False hope: the tests were buggy. [CI tests pass now](https://github.com/groue/GRDB.swift/actions/runs/4706738418/jobs/8348656299)

**Comment by groue** [comment] 2023-04-15 10:06
Re-reading the code in order to look for a logic bug, I pushed in fcfd6e9028cf5b7b9922abc528385b77c3d5face, available on the `development` branch, an enhancement to `ValueConcurrentObserver`. The reader connection that has fetched the initial observed is released _earlier_ (making it available for other reads or observations). This change is not supposed to address this issue, but who knows.

**Comment by mattgallagher** [comment] 2023-04-17 13:19
No fix in https://github.com/groue/GRDB.swift/commit/fcfd6e9028cf5b7b9922abc528385b77c3d5face, unfortunately.

A little more information about the scenario, as I see it...

1.  A transaction is written to a table
2. This triggers each of the many value observers of this table
3. Each of the observers grabs a WALSnapshotTransaction (each of which holds an itemsSemaphore)
4. Each of the observer threads blocks waiting for queue in SerializedDatabase.async
5. A writer (possibly the original writer) holding the queue in a transaction and as part of databaseDidCommit tries to call Pool.get but the itemsSemaphore is held by all the observers

Leading to a deadlock.

**Comment by mattgallagher** [comment] 2023-04-17 13:28
So while I showed *a* thread in the previous screenshot, I think the thread responsible for the deadlock is this one.

<img width="431" alt="Screenshot 2023-04-17 at 23 27 01" src="https://user-images.githubusercontent.com/28080/232498050-89ef74c9-74c1-487b-8733-e9c719ddc01b.png">

**Comment by groue** [comment] 2023-04-17 14:10
Do you think it's possible to see all threads? `bt all` in lldb.

**Comment by mattgallagher** [comment] 2023-04-17 23:33
It is definitely a deadlock, not simply starvation. The writer is holding the `queue` and waiting for `itemSemaphore` which it will never get. The `itemsSemaphore` is meanwhile held by the observers who are all waiting for the `queue` which they will never get.

I'll try to construct a simple test case and follow up.

**Comment by diatoming** [comment] 2023-04-18 00:13
Hi, i'm not sure whether this info is useful or not. 

But i found that if you are using DatabasePool with v6.10 in your app, after open the sqlite file with **DB Browser for SQLite.app**, do nothing and just quit, which seems triggered something. Then relaunch your app, you will get SQL logic error, and the data can not be read anymore with pool, instead you can read data with DatabaseQueue.

**Comment by mattgallagher** [comment] 2023-04-18 03:09
I created a test that demonstrates the issue. I had to cheat the test timing by inserting a sleep (so it's not for merging) but it demonstrates how observers can block the writing queue and vice versa, leading to a deadlock.

https://github.com/groue/GRDB.swift/pull/1364

**Comment by groue** [comment] 2023-04-18 07:44
> Hi, i'm not sure whether this info is useful or not.
> 
> But i found that if you are using DatabasePool with v6.10 in your app, after open the sqlite file with **DB Browser for SQLite.app**, do nothing and just quit, which seems triggered something. Then relaunch your app, you will get SQL logic error, and the data can not be read anymore with pool, instead you can read data with DatabaseQueue.

Hi @diatoming. This looks like an entirely distinct issue. Maybe DB Browser for SQLite.app deletes the -shm and -wal files next to the database file, preventing your app from opening a read-only connection on the database. If this is the case, then there's nothing I can do: reads on a WAL database *require* those files. GRBD takes care of creating them when opening a connection, but it's not responsible if DB Browser for SQLite.app messes with this setup. Anyway, this is my hypothesis. If something different is happening, please open a distinct issue and provide the requested details.

**Comment by groue** [comment] 2023-04-19 06:48
This issue (the deadlock) is currently addressed in #1364.

**Closed** 2023-04-29 14:35 UTC
Labels: bug
