### ISSUE TITLE
Async bug? (reads not seeing writes in sequential async code)

### ISSUE THREAD

**Issue by marchy** [groue/GRDB.swift#1456] opened 2023-11-10 20:58 UTC
Hi there, I am seeing a really unexpected behaviour and I wanted to verify if this is working as expected or a bug as part of the [🔥 EXPERIMENTAL](https://github.com/groue/GRDB.swift/blob/master/README.md#what-are-experimental-features) Swift `async` support.

The scenario is simply fetching remote results, writing them into the DB, and immediately reading them back – expecting that we get the results we just written – however we do not see the results that were just written.

``` Swift
func syncThings() -> async throws [Thing] {
	let remoteData = /*fetch remote data*/ await ...

	// persist
	try await _persist( remoteData: remoteData )

	// fetch local
	let localData:[Thing] = try await _fetchLocal()
	return localData


	@Sendable func _persist( remoteData:[Thing] ) async throws {
		try await database.writer.write { (database:Database) in
			for thing:Things in remoteData {
				try thing.toDAO().upsert( database )
			}
		}
		print( "DEBUG: Persisted \(remoteData.count) things" )
	}

	@Sendable func _fetchLocal() async throws -> async throws [Thing] {
		let things:[Thing] = try await database.reader.read { (database:Database) in
			try ThingDAO.fetchAll( database )
		}
		print( "DEBUG: Loaded \(things.count) things" )
		return things
	}
}


struct ThingDAO : FetchableRecord, PersistableRecord {
	... // nothing fancy
}
```

The debug output shows the following:
```
DEBUG: Persisted 217 things
DEBUG: Loaded 0 things
```
... however if we add an arbitrary delay between the `_persist()` and `_fetchLocal()` calls (or just put a breakpoint in between them and resume), we get the expected output:
```
DEBUG: Persisted 217 things
DEBUG: Loaded 217 things
```

In terms of the `database.reader` and `database.writer` instance, they both refer to the same singleton instance accessed app-wide as per the GRDB demo apps and [Concurrency page](https://swiftpackageindex.com/groue/grdb.swift/v6.21.0/documentation/grdb/concurrency) guidance.
ie: 
``` Swift
class AppDatabase {
	var reader:DatabaseReader{ writer }
	let writer:any DatabaseWriter
}
```

It is my understanding that the `async` `.write{ .. }` call would guarantee that the write transaction is fully flushed to the DB before it finishes, thus any subsequent access to a `.read{ .. }` in the sequential block of code above should see those changes.

From the documentation of [read](https://swiftpackageindex.com/groue/grdb.swift/v6.21.0/documentation/grdb/databasereader/read(_:)-4w6gy)/[write](https://swiftpackageindex.com/groue/grdb.swift/v6.21.0/documentation/grdb/databasewriter/write(_:)-88g7e), it does mention that there is such a thing as "eventual concurrent writes" potentially at play:

> "Database operations are isolated in a transaction: they do not see changes performed by eventual concurrent writes (even writes performed by other processes)."

– however the code above is sequential not concurrent, and is all executed by the same process and through the same `DatabaseWriter` instance.

At a loss for what might be happening under the covers and how to troubleshoot further.... 🙏

**Comment by groue** [comment] 2023-11-11 10:34
Hello @marchy,

Thank you for the report.

First, I'll confirm your expectations.

> It is my understanding that the `async` `.write{ .. }` call would guarantee that the write transaction is fully flushed to the DB before it finishes, thus any subsequent access to a `.read{ .. }` in the sequential block of code above should see those changes.

This is correct. And I'm pretty positive the code does exactly this, and has always done so since the introduction of async methods in GRDB. So I won't ask which GRDB version you are running.

> From the documentation of [read](https://swiftpackageindex.com/groue/grdb.swift/v6.21.0/documentation/grdb/databasereader/read(_:)-4w6gy)/[write](https://swiftpackageindex.com/groue/grdb.swift/v6.21.0/documentation/grdb/databasewriter/write(_:)-88g7e), it does mention that there is such a thing as "eventual concurrent writes" potentially at play:
> 
> > "Database operations are isolated in a transaction: they do not see changes performed by eventual concurrent writes (even writes performed by other processes)."
> 
> – however the code above is sequential not concurrent, and is all executed by the same process and through the same `DatabaseWriter` instance.

Your are correct again. If the read and the write were concurrent, the read could start a transaction before the write has committed to disk, and see the old state of the database. However, since they are sequential, the write and read transactions are serialized, and the read must definitely see a database whose state has been impacted by the write.

---

In the end, we have a program that does not behave as the theory says, so some assumption has to be revised 😅 

**Maybe GRDB has a bug indeed.** Yet I could not reproduce. The test below passes 10000 times without failure, on both macOS and an iOS 17.0 simulator:

<details><summary>The test</summary>

This test should fail with "table not found: t" if a read would start before the write:

```swift
func testAsyncWriteThenRead() async throws {
    func test(_ dbWriter: some DatabaseWriter) async throws {
        try await dbWriter.write { db in
            try db.execute(sql: """
                CREATE TABLE t (id INTEGER PRIMARY KEY);
                INSERT INTO t VALUES (1);
                """)
        }
        
        let count = try await dbWriter.read { db in
            try Table("t").fetchCount(db)
        }
        
        XCTAssertEqual(count, 1)
    }
    
    try await test(makeDatabaseQueue())
    try await test(makeDatabasePool())
}
```

</details>

**Maybe some concurrent write happens between our write and read**. Performing a write then a read sequentially does not guarantee that the read will see the database in the exact same state as it was left by the write. Some other write could mess with the database state in between:

```swift
try await _persist(remoteData: remoteData)
// <- Here be dragons
let localData: [Thing] = try await _fetchLocal()
```

I'm not saying that this is what happens, because you mention that a delay or a breakpoint fixes the original issue. 

But the question remains.

And if your app *relies* on the fetch to load *exactly* what was written, then I must make it very clear that the code you have shared does not preserve this invariant.

**Other assumptions scare me**: unexpected SQLite behavior, or unexpected Swift concurrency runtime behavior.

We are probably missing something else 😅 

I would suggest helping reproducing the problem. It's difficult to help without something to chew on.

**Comment by marchy** [comment] 2023-11-12 17:59
Thanks for the stellar response @groue – and let me take the time to say about the library as a whole (happy migrator away from Realm here – let's not even speak of CoreData / SwiftData) 😄


Your clues are helping zone in on the culprit:
> Maybe some concurrent write happens between our write and read.

\>> This is indeed the case. We have 4 other concurrent operations that all fetch remote data and persist to the DB in the same way.
_NOTE: These are all on separate entities (ie: separate DB tables), and if it matters they also have no DB associations between them, as we manage all associations within our uniquing in-memory architecture (ie: singleton model object instance per ID of that entity). Perhaps SQLite keeps writing to the WAL file before copying it to the master DB file regardless of whether multiple concurrent transactions have the potential to affect each other across tables or not (goes way beyond my SQLite understanding)._

**TEST 1: When changing them to happen serially instead of concurrently >> issue goes away (ie: read-then-write behaviour is as expected – no stale reads occur)**

This confirms it the concurrent transactions that is surfacing the problem.

**TEST 2: Read using DB queue instead of DB pool >> issue still happens**

After scourging through the [Concurrency](https://swiftpackageindex.com/groue/grdb.swift/v6.21.0/documentation/grdb/concurrency) and [SQLite isolation](https://www.sqlite.org/isolation.html) docs, I would have thought the stale reads behaviour would be guaranteed to not happen if using a `DatabaseQueue` rather than a `DatabasePool` (as we are in our app) – however surprisingly it happens with the queue as well.

Could you clarify the following?
> Performing a write then a read sequentially does not guarantee that the read will see the database in the exact same state as it was left by the write. Some other write could mess with the database state in between.

The queue approach ought to eliminate any other writes happening concurrently under any circumstances, no?


**TEST 3: Read using a write block operation >> issue still happens**
ie: Instead of `database.reader.read{ /*read here*/ }`, perform `database.writer.write{ /*read here*/ }` for the read op. ⚠️  This still produces the stale reads behaviour – under both DB queue and DB pool modes.

This confirms there is a failure in my understanding of the invariants guaranteed, as it seems to contradict this image (since 'Read State B' returns 'Read State A' which is stale):
![DatabaseQueueScheduling~dark@2x](https://github.com/groue/GRDB.swift/assets/1369360/b55518ba-b4ec-4d46-b87a-76331fd5787d) as well as this statement from the [Concurrent Thinking](https://swiftpackageindex.com/groue/grdb.swift/v6.21.0/documentation/grdb/concurrency#Concurrent-Thinking) section of the Concurrency page docs:

> You are sure, when you perform a write access, that you deal with the latest database state on disk.

It seems here a subsequent write is seeing a stale version of the data.

**Comment by groue** [comment] 2023-11-13 12:28
> I'd be happy to add in the necessary concurrent access to repro the issue – since it's completely stable / happens every time.

If you have a repro, then it would definitely help me helping you!

You can share a project or some sample code, with a list of steps to perform that reproduce the problem (ideally: "1. do this, 2. look there, and see how it prints x instead of y as expected")

It definitely helps a lot when as much useless code as possible is removed from such sample code (abstraction layers included - nobody likes to cry peeling an onion when debugging). Pretty often, such layers are exactly what creates the problem in the first place - because they are ill-designed and prevent the developer from exercising control. Yes, I *do* mean that building a simple repro without cruft can help revealing the origin of the problem, even if I can't assert this is the problem in your code base, of course.

**Comment by groue** [comment] 2023-11-13 12:38
> **TEST 2: Read using DB queue instead of DB pool >> issue still happens**
> 
> After scourging through the [Concurrency](https://swiftpackageindex.com/groue/grdb.swift/v6.21.0/documentation/grdb/concurrency) and [SQLite isolation](https://www.sqlite.org/isolation.html) docs, I would have thought the stale reads behaviour would be guaranteed to not happen if using a `DatabaseQueue` rather than a `DatabasePool` (as we are in our app) – however surprisingly it happens with the queue as well.
> 
> Could you clarify the following?
> 
> > Performing a write then a read sequentially does not guarantee that the read will see the database in the exact same state as it was left by the write. Some other write could mess with the database state in between.
> 
> The queue approach ought to eliminate any other writes happening concurrently under any circumstances, no?

Yes, a `DatabaseQueue` serializes accesses to a single connection, so the read should definitely see what has just been written (unless it was undone by some other write).

To illustrate (I can write SQL statements one below the other, because everything is strictly serialized by `DatabaseQueue`):

```sql
-- The write
BEGIN;
DELETE FROM player;
INSERT INTO player VALUES ('Arthur');
COMMIT;

-- The read
BEGIN;
-- Fetch 1 🙂
SELECT COUNT(*) FROM player;
COMMIT;
```

The nasty scenario I try to warn against is when another write is performed in between:

```sql
-- The write
BEGIN;
DELETE FROM player;
INSERT INTO player VALUES ('Arthur');
COMMIT;

-- Surprise! Sneaky write performed by some app other component
BEGIN;
DELETE FROM player; -- lol
END;

-- The read
BEGIN;
-- Fetch 0 😱
SELECT COUNT(*) FROM player;
COMMIT;
```

The more I think about it, the more I think you'd get a better understanding of what's happening if you would log all SQL statements as below:

```swift
var config = Configuration()

config.prepareDatabase { db in
    let label = db.description
    db.trace {
        logger.debug("\(label)> \(String(describing: $0))")
    }
}

#if DEBUG
// Protect sensitive information by enabling verbose debugging in
// DEBUG builds only.
// See <https://swiftpackageindex.com/groue/grdb.swift/documentation/grdb/configuration/publicstatementarguments>
config.publicStatementArguments = true
#endif

// Or DababaseQueue
let dbPool = try DababasePool(path: ..., configuration: config)
```

In the log, you'd see exactly which connection is doing what (the writer and the readers).

**Comment by marchy** [comment] 2023-11-15 15:53
Thanks @groue.

Regarding the single VS separate/distinct transactions, I did realize that (admittedly not at first) however I didn't write a fourth test for it, since as you mention there are other layers in the onion and it was not trivial/possible to lift up one transaction and share it across multiple sequential domain operations (ie: would need to refactor to pass along the same transaction/database instance across a higher-level operation).
_ASIDE: I'm assuming GRDB has no way of passing along [explicit transactions](https://learn.microsoft.com/en-us/ef/core/saving/transactions#using-external-dbtransactions-relational-databases-only) or [ambient transactions](https://learn.microsoft.com/en-us/ef/core/saving/transactions#using-systemtransactions) as does .NET's Entity Framework, correct?_

However the more important and definitely more surprising part in this case is not that something else may write a value "in between" the two transactions – it's that there is nothing else that is writing to that same table (only to the same DB) – and yet the second transaction still doesn't see the result of the first, awaited transaction.

In terms of ORM semantics this is downright scary – because it means the `await` of a given transaction cannot be trusted. In this case, there seems to be no guarantee that the awaited transaction has actually been committed into the database yet! If SQLite is doing certain background compacting / copying over a the "just-committed" transaction into a separate WAL file, and it will only "eventually" copy that back over to the main database file to be visible by a subsequent sequentially-issued query – this is actually NOT an ignorable detail that the level of abstraction the code is written against (ie: the ORM) can be built to ignore.

Basically the "fetch a random value" aspect is okay – so long as that value is a "random" NEWER value than the first transaction. To get a "random" OLDER value makes no sense, and is a leak of abstraction from the database which the ORM ought to account for (ie: when you 'await' a transaction that finishes successfully... you have to be able to trust that the mutations performed by that transactions are fully visible to subsequently-issued queries).


For the time being we had to re-architect away from treating the DB as the source of truth to treating our in-memory, uniquing domain model as our source of truth – which I understand is generally against GRDB's design goals/philosophy, and has been an internal toss-up on which way we should go architecturally, which this issue decisively made clear.  :)

I will make a point to get a sample project set up to be able to fully repro this in an isolated sharable project – but unfort we're amidst a crunched release so I need to schedule it in a few weeks time. I appreciate your patience on it. 🙏

**Comment by groue** [comment] 2023-11-15 16:47
> Thanks @groue.
> 
> Regarding the single VS separate/distinct transactions, I did realize that (admittedly not at first) however I didn't write a fourth test for it, since as you mention there are other layers in the onion and it was not trivial/possible to lift up one transaction and share it across multiple sequential domain operations (ie: would need to refactor to pass along the same transaction/database instance across a higher-level operation). _ASIDE: I'm assuming GRDB has no way of passing along [explicit transactions](https://learn.microsoft.com/en-us/ef/core/saving/transactions#using-external-dbtransactions-relational-databases-only) or [ambient transactions](https://learn.microsoft.com/en-us/ef/core/saving/transactions#using-systemtransactions) as does .NET's Entity Framework, correct?_

It looks like the equivalent of the linked "Explicit transactions" is the plain `write`:

```swift
let writer: some DatabaseWriter = ...

try writer.write { db in // using var transaction = connection.BeginTransaction(); try {
    // var command = connection.CreateCommand();
    // command.Transaction = transaction;
    // command.CommandText = "DELETE FROM dbo.Blogs";
    // command.ExecuteNonQuery();
    try db.execute("DELETE FROM dbo.Blogs")

    // var options = new DbContextOptionsBuilder<BloggingContext>()
    //     .UseSqlServer(connection)
    //     .Options;
    // 
    // using (var context = new BloggingContext(options))
    // {
    //     context.Database.UseTransaction(transaction);
    //     context.Blogs.Add(new Blog { Url = "http://blogs.msdn.com/dotnet" });
    //     context.SaveChanges();
    // }
    try Blog(url: "http://blogs.msdn.com/dotnet").insert(db)
} // transaction.Commit(); }
```

There are more transactions methods, for more advanced usages: [Transactions and Savepoints](https://swiftpackageindex.com/groue/grdb.swift/v6.21.0/documentation/grdb/transactions). 

Transactions are always explicit, because the library puts the developer in charge of delimiting transaction boundaries. This is the [Rule 2](https://swiftpackageindex.com/groue/grdb.swift/v6.21.0/documentation/grdb/concurrency#Rule-2-Mind-your-transactions) of GRDB concurrency. This does not sound fun, but well transactions are just so important! 🤓

I'm not sure GRDB has any concept of "ambient transactions", but you can build your own (if I understand correctly what an ambiant transaction is). Developers who want to build composable pieces of code that can be reused in various transactions design methods that accept a `Database` argument. Those are generally private, so that the public api only exposes the desired transactions.:

```swift
// Methods that perform transactions
public func frobnicate() throws {
    try dbWriter.write { db in
        try composable1(db)
    }
}

public func doStuff() throws {
    try dbWriter.write { db in
        try composable1(db)
        try composable2(db)
    }
}

// Methods that do not open transactions
private func composable1(_ db: Database) throws {
    try ...
}

private private func composable2(_ db: Database) throws {
    try ...
}
```

In the end, write transactions are always expressed in the structure of the code. There is no long-lived write transactions in GRDB. You can't build a `Transaction` object and keep it alive as long as you want. This is by design: while [locked](https://www.sqlite.org/lockingv3.html) by a transactions, all database accesses throw SQLITE_BUSY. By not exposing any `Transaction` class, GRDB just avoids putting a gun in the hands of the developer 🦶🔫

There are some long-lived *read-only* transactions: [`DatabaseSnapshot`](https://swiftpackageindex.com/groue/grdb.swift/v6.21.0/documentation/grdb/databasesnapshot) and [`DatabaseSnapshotPool`](https://swiftpackageindex.com/groue/grdb.swift/v6.21.0/documentation/grdb/databasesnapshotpool), but they address very distinct use cases.

> However the more important and definitely more surprising part in this case is not that something else may write a value "in between" the two transactions – it's that there is nothing else that is writing to that same table (only to the same DB) – and yet the second transaction still doesn't see the result of the first, awaited transaction.

Yes. I'm eager to see a repro.

> In terms of ORM semantics this is downright scary – because it means the `await` of a given transaction cannot be trusted. In this case, there seems to be no guarantee that the awaited transaction has actually been committed into the database yet! If SQLite is doing certain background compacting / copying over a the "just-committed" transaction into a separate WAL file, and it will only "eventually" copy that back over to the main database file to be visible by a subsequent sequentially-issued query – this is actually NOT an ignorable detail that the level of abstraction the code is written against (ie: the ORM) can be built to ignore.

Yes, totally. Now I trust SQLite 99.9% for its super solid semantics. And even if I only trust Swift concurrency 90%, the `Continuation` is only resumed after the write was committed on disk (`COMMIT` success). So our preferred hypothesis should remain a GRDB or an application bug. We definitely need a repro.

> For the time being we had to re-architect away from treating the DB as the source of truth to treating our in-memory, uniquing domain model as our source of truth – which I understand is generally against GRDB's design goals/philosophy, and has been an internal toss-up on which way we should go architecturally, which this issue decisively made clear. :)

I've been using SQLite through GRDB as the source of truth for years, because it is indeed the goal of the library. I hope we can make progress in this issue and find the origin of the problem. I'm very very eager to fix a GRDB bug if there is one.

> I will make a point to get a sample project set up to be able to fully repro this in an isolated sharable project – but unfort we're amidst a crunched release so I need to schedule it in a few weeks time. I appreciate your patience on it. 🙏

That would be really helpful :-)

**Comment by groue** [comment] 2023-11-26 09:42
@marchy, I'm closing this issue, due to the lack of reproducing case. The hypothesis of an application bug was not completely discarded, and my own tests did not reveal any problem. Issues don't remain open in this repo, unless someone is actually dealing with it. Please do reopen when you can spot an actual GRDB issue!

**Closed by groue** 2023-11-26 09:42 UTC

**Comment by marchy** [comment] 2023-11-28 02:11
@groue We've finally had the chance to chase this further – as I mentioned we've been in a release crunch and needed a few weeks to schedule the repro.

After throwing a number of scenarios at it with multiple async transactions writing in parallel, we discovered a timing issue within our own codebase which was causing us to perceive the read as coming back empty where in practice there was a double-write happening in parallel which made the read return empty if it happened "between" them.

I really appreciate your guidance on all the above – and relieved that it wasn't something wild going on from the Sqlite or GRDB stack!

**Comment by groue** [comment] 2023-11-28 06:50
Good news, @marchy! I'm happy you could fix the original issue in the app. And thank you for your help in checking the robustness of GRDB. Have a good release, and come back whenever you have a new question!
