### ISSUE TITLE
Generic Parameter 'T'could not be inferred

### ISSUE THREAD

**Issue by mtissington** [groue/GRDB.swift#53] opened 2016-05-18 12:15 UTC
`        dbQueue.inDatabase { db in
            let expandedText = String.fetchOne(db, "SELECT expandedText FROM words")
               return expandedText
        }`

Am I missing something here?
What is wrong with this?

**Comment by groue** [comment] 2016-05-18 12:26
Hello @mtissington 

> What is wrong with this?

Let me do a wild guess: you're getting a `Generic parameter T could not be inferred` error.

Assuming I'm right, here is the reason why, and the way to avoid that error:

There are two ways to use the inDatabase method:

```swift
dbQueue.inDatabase { db in
    // do some stuff
}

let value = dbQueue.inDatabase { db in
    return ... // return some stuff
}
```

In your case, you return a value, but don't use it outside: the poor Swift compiler infers that the inDatabase call should both have a value (returned from inside), and have no value (since nothing is consumed), and collapses. I tend to think its a Swift bug.

The fix is not to return anything, or to use the returned value.

Since you're the second person who asks that question, I think I should at least update the FAQ ;-)

**Comment by groue** [comment] 2016-05-19 06:12
@mtissington, I've just been bitten in an unexpected way myself. Sometimes you also have to explicitly declare the type of the returned value:

```swift
// Variant 1
let value: MyType = dbQueue.inDatabase { db in
    return ...
}

// Variant 2
let value = dbQueue.inDatabase { db -> MyType in
    return ...
}
```

I have to do something about this: I reopen this issue.

**Comment by mtissington** [comment] 2016-05-19 06:41
as  an fyi i like how you have packaged this all up, for the most part it works quick and is easy to us. thanks!

**Comment by groue** [comment] 2016-05-19 06:42
@mtissington That's the best thing a library writer can read 😄 Happy GRDB!

**Comment by groue** [comment] 2016-05-19 21:35
Little update: the problem is still there in Swift 3, and I could not find any workaround. At least I have enough matter for a bug report on http://bugs.swift.org.

**Comment by groue** [comment] 2016-05-20 06:09
Swift issue created: https://bugs.swift.org/browse/SR-1570

**Comment by groue** [comment] 2016-05-20 06:26
@mtissington I close this issue: there's nothing I can do but waiting for [SR-1570](https://bugs.swift.org/browse/SR-1570) to be fixed. I hope the [FAQ](https://github.com/groue/GRDB.swift#faq) will help other users. Thanks for the report!

**Closed by groue** 2016-05-20 06:26 UTC
Labels: enhancement
