### ISSUE TITLE
Queries fail with SQLCipher 3, but only in release mode

### ISSUE THREAD

**Issue by fabiorodella** [groue/GRDB.swift#641] opened 2019-11-01 14:37 UTC
### What did you do?

I recently migrated a project from GRDBCipher 3 to 4. I wanted to keep using SQLCipher 3 for now to avoid having to deal with conversions and compatibility modes, so I made the following change (which according to the docs is a supported configuration):

```
-    pod 'GRDBCipher', '3.3.1'
+    pod 'GRDB.swift/SQLCipher', '4.5.0'
+    pod 'SQLCipher', '3.4.2'
```

After I made the necessary code changes everything looked good when running locally, but when I deployed the build to TestFlight and installed it on a few devices I noticed that all `SELECT` queries were failing with this error:

```
SQLite error 7 with statement `SELECT rowid, json FROM task`: not an error
```

This particular query happens to be the first `SELECT` I do in one of the migration steps after creating the tables. The same error happens in other queries even if I'm using an existing database that was created/migrated with the previous `GRDBCipher` version.

As I mentioned before, this happens only in release builds (TestFlight or ad-hoc), while local builds running through Xcode (simulator or device) work fine.

### What did you expect to happen?

Queries should work as before.

### What happened instead?

All queries throw the mentioned error

### Environment

**GRDB flavor(s):** `GRDB.swift/SQLCipher 4.5.0` and `SQLCipher 3.4.2`
**Installation method:** Cocoapods
**Xcode version:** 11.1 (11A1027)
**Swift version:** 5.1
**Platform(s) running GRDB:** iOS
**macOS version running Xcode:** 10.14.6 (18G103)

### Demo Project

Unfortunately, it's a bit tricky to come up with a demo project since the error only happens in release builds.

**Comment by groue** [comment] 2019-11-01 17:17
Hello @fabiorodella, thanks for the report. I'll try to reproduce the bug by compiling a sample app in release configuration.

It will take a few days, because I'm not close to my computer at the current time. Meanwhile, you can perform additional investigation about this error 7. Maybe you'll find an explanation on your own?

**Comment by michaelkirk-signal** [comment] 2019-11-01 17:52
> . The same error happens in other queries even if I'm using an existing database that was created/migrated with the previous GRDBCipher version

Can you clarify a bit more - are you seeing this error on databases that were newly created after upgrading SQLCipher?

Or are you seeing this error *only* when running queries against legacy databases that existed *before* they go the upgraded version?

For the avoidance of doubt, can you include the diff from your Podfile.lock to show the precise changes to to underlying SQLCipher dependency across your update?

I just wanted to rule out any incompatibility with SQLCipher configuration changes across versions.

In particular, this snippet from the [README](https://github.com/groue/GRDB.swift#creating-or-opening-an-encrypted-database) might be relevant if you changed the underlying SQLCipher version from 3 to 4.

```
// Open an SQLCipher 3 database with SQLCipher 4
var config = Configuration()
config.prepareDatabase = { db in
    try db.usePassphrase("secret")
    try db.execute(sql: "PRAGMA cipher_compatibility = 3")
}
let dbQueue = try DatabaseQueue(path: dbPath, configuration: config)
```

**Comment by fabiorodella** [comment] 2019-11-03 15:34
> It will take a few days, because I'm not close to my computer at the current time. Meanwhile, you can perform additional investigation about this error 7. Maybe you'll find an explanation on your own?

Thank you! According to the SQLite docs (https://sqlite.org/c3ref/c_abort.html) error 7 is defined as 
`SQLITE_NOMEM` and described as `A malloc() failed`. I wish I could debug the code while running, but it doesn't seem to be possible since the issue only manifests itself on release...

> Can you clarify a bit more - are you seeing this error on databases that were newly created after upgrading SQLCipher?

Sorry, I could have been clearer. I'm seeing this both with databases that were created with a previous version of GRDBCipher **and also** when creating a brand new database.

> For the avoidance of doubt, can you include the diff from your Podfile.lock to show the precise changes to to underlying SQLCipher dependency across your update?

Sure thing, here you go:
```
PODS:
-  - GRDBCipher (3.3.1):
-    - SQLCipher (~> 3.4.1)
+  - GRDB.swift/SQLCipher (4.5.0):
+    - SQLCipher (>= 3.4.0)
...
DEPENDENCIES:
-  - GRDBCipher (= 3.3.1)
+  - GRDB.swift/SQLCipher (= 4.5.0)
+  - SQLCipher (= 3.4.2)
```

> In particular, this snippet from the README might be relevant if you changed the underlying SQLCipher version from 3 to 4.

The thing is I _wanted_ to keep SQLCipher at version 3, at least as a initial migration step, before moving on to converting or using a compatibility mode with version 4. According to docs, this should be supported.

However, since creating this issue I've been running some tests by upgrading to SQLCipher 4 and creating a database from scratch, but I've also been running into some very weird crashes caused by a segfault, again only in release mode. I'm not able to get the full crash report right now, but I'll post it here later.

**Comment by groue** [comment] 2019-11-04 11:58
@fabiorodella I wrote a [tiny app](https://github.com/groue/GRDBIssue641) which opens an encrypted database and reads from it. I could successfully archive it and run it on a device.

As far as I can tell, any problem your app is facing is not in the GRDB repository. You have to further reduce your issue in order to find the root cause.

**Comment by fabiorodella** [comment] 2019-11-04 16:50
@groue thank you very much for trying it out. I downloaded your sample project and made some changes to make it closer to my original project (dropped the deployment target to iOS 10, created the database file inside an app group container) and indeed the error does not manifest itself.
I'll keep trying to get to the bottom of this and will report back at some point, but in the meantime feel free to close this issue. Thanks again!

**Comment by groue** [comment] 2019-11-04 16:55
> I'll keep trying to get to the bottom of this and will report back at some point, but in the meantime feel free to close this issue.

We can wait a few days before closing the issue.

**Comment by fabiorodella** [comment] 2019-11-04 19:10
OK, I think I have narrowed down the issue, and it's a doozy... I can get your sample app to crash by making these two changes:
- creating the database file inside an app group container, like so:
```
let sharedContainerUrl = FileManager.default.containerURL(forSecurityApplicationGroupIdentifier: "your.group.id")!
let databaseURL = sharedContainerUrl.appendingPathComponent("db.sqlite", isDirectory: false)
```
- adding the Firebase analytics pod to the podfile. Note that _I don't even have to try to initialize it, just adding the pod is enough_.
```
pod 'Firebase/Analytics', '6.11.0'
```

I also confirmed that removing the Firebase pod gets rid of the error in my original app.

For the sake of my sanity, could you please confirm if you get the same result @groue ?

**Comment by groue** [comment] 2019-11-04 19:32
> For the sake of my sanity, could you please confirm if you get the same result @groue ?

Still no issue here: [this commit](https://github.com/groue/GRDBIssue641/commit/35fc7f713042fe0f3d4443377cf4c7344edb812e) in the sample app runs fine.

**Comment by fabiorodella** [comment] 2019-11-04 19:37
Yeah, sorry for the trouble, I ended up deleting my comment, but not soon enough.

**Comment by groue** [comment] 2019-11-11 09:51
No news is good news, @fabiorodella. I suppose I can close this issue now.

**Closed by groue** 2019-11-11 09:51 UTC
Labels: support

**Comment by fabiorodella** [comment] 2019-11-11 13:28
Hi @groue, I spent 3 days last week on this problem, and all I can say with certainty is:
- removing the `Firebase/Analytics` pod from my project gets rid of the issue entirely. In fact, I narrowed it down to a specific sub-pod, `GoogleAppMeasurement`.
- just the mere presence of this pod is enough to cause the issue, even I'm not importing or initializing the framework at all. To me this seemed to point at some kind of flag being added to the build process, but I looked at the `xcconfig` file for the pod and adding the same flags manually to my project has no effect.
- adding these pods to your sample project does _not_ cause any issues

All of these things definitely point to the root cause being outside of GRDB, so closing the issue sounds good. To unblock us, for now we are just shipping release builds without Firebase Analytics, and I will resume the investigation at some point in the future. I want to have a clear minimal reproduction case to be able to open an issue with Firebase.

If I ever do figure out what's going on, I'll be sure to write back here.

Thanks again for your help!

**Comment by fabiorodella** [comment] 2020-01-23 16:32
@groue I finally had some more time to play with this issue today, and I think I figured out a way to make your sample app crash in the same way as mine. Can you please try adding these lines _inside_ the migration block (`AppDelegate.swift:35`):
```
let rows = try Row.fetchCursor(db, sql: "SELECT * FROM player")
while let row = try rows.next() {
}
```
It looks like the call to `RowCursor.next` inside a migration block somehow triggers this error. My assumption about the app group container having something to do with it was a red herring, the issue will happen regardless of the location of the database file.

Once the code is in that state, any of these following actions will get rid of the crash:
- Removing the `Firebase/Analytics` pod
- Replacing the cursor iteration with `Row.fetchAll`
- Removing the `@inlinable` attribute from `RowCursor.next`

Upgrading Firebase to the latest version available also had no effect.

**Comment by groue** [comment] 2020-01-23 18:20
Thanks for your reports, @fabiorodella!

> Removing the Firebase/Analytics pod

That reminds me of https://github.com/RxSwiftCommunity/RxGRDB/issues/59. Some conflict between SQLCipher and the stock SQLite.

> Replacing the cursor iteration with `Row.fetchAll`

That's weird, because `fetchAll` always eventually calls `fetchCursor`: https://github.com/groue/GRDB.swift/blob/v4.9.0/GRDB/Core/Row.swift#L864-L872

Maybe the problem happens when the cursor is turned into an array by copying the row: https://github.com/groue/GRDB.swift/blob/v4.9.0/GRDB/Core/Row.swift#L113-L126

> Removing the @inlinable attribute from RowCursor.next

Now I'm clueless 😅

**Comment by MrShafiee** [comment] 2020-06-02 15:19
Hi @groue, is there any update for this ticket?
I have firebase in my project, and exactly have the same issue!
App works fine when run from xcode and  will be crash when run from Testflight!
I faced with this crash for this query:
```
try database.read { db in
   let rows = try Row.fetchCursor(db, sql: "select * from User order by id")
   while let row = try rows.next() {
      users.append(UserModel(row: row))
   }
}
```

and I install GRDB from pod with cipher:
```
pod 'GRDB.swift/SQLCipher
pod 'SQLCipher', '~> 4.0'
```

**Comment by groue** [comment] 2020-06-02 15:29
Hello @MrShafiee. This ticket is closed. Nobody works on it. Firebase comes with SQLite, and SQLite conflicts with SQLCipher. Ask Firebase how to use it with your build of SQLCipher, maybe?

**Comment by MrShafiee** [comment] 2020-06-02 16:12
@groue thanks for your answer, but do you think they will do anything for that really!?! 
btw my problem solved by @fabiorodella hints! I did this:

- Replacing the cursor iteration with Row.fetchAll

**Comment by groue** [comment] 2020-06-02 16:42
OK, maybe I had a too quick answer. But if you have a workaround, I don't feel much pressure myself for investigating this particular context. Contributions are welcome!

**Comment by fabiorodella** [comment] 2020-06-02 16:54
Hey @MrShafiee, at some point my code started breaking in different non-deterministic ways even with the "workarounds" I previously posted here. The only sure-fire way to get rid of the issue was to add this to my podfile:

```
post_install do |installer|
  installer.pods_project.targets.each do |target|
    # Loop through the targets and remove explicit linking to the system SQLite framework. We do
    # that because SQLCipher embeds a copy of SQLite, and using both at the same time can cause
    # weird crashes. This will just force all dependencies to use the embedded one.
    target.build_configurations.each do |config|
      if (config != nil && config.base_configuration_reference != nil)
        xcconfig_path = config.base_configuration_reference.real_path
        xcconfig = File.read(xcconfig_path)
        new_xcconfig = xcconfig.sub('-l"sqlite3"', '')
        File.open(xcconfig_path, "w") { |file| file << new_xcconfig }
      end
    end
  end
end
```

I never had time to raise an issue with Firebase, but I'm not sure if they'd be able to do something.

**Comment by groue** [comment] 2020-06-16 10:07
Check https://forums.swift.org/t/grdb-sqlcipher-crash-release-builds-only-solved/37598 for a potential solution to this issue.
