### ISSUE TITLE
WAL file left behind after close.

### ISSUE THREAD

**Issue by scottandrew** [groue/GRDB.swift#418] opened 2018-09-25 00:20 UTC
### What did you do?

Create a simple database with that open's a DBPool and closes it by setting the pool to nil.

### What did you expect to happen?

The write ahead files to disappear.

### What happened instead?

The write ahead files are left behind with data in them.

### Environment

**GRDB flavor(s):** GRDB
**GRDB version:** 3.3.0
**Installation method:** CocoaPods
**Xcode version:** 10.0
**Swift version:** 4.2
**Platform(s) running GRDB:** macOS
**macOS version running Xcode:** 10.12

### Demo Project

[GDRB Issue.zip](https://github.com/groue/GRDB.swift/files/2413325/GDRB.Issue.zip)

**Comment by groue** [comment] 2018-09-25 06:19
Hello @scottandrew,

The DatabasePool class opens your database in the [WAL mode](https://www.sqlite.org/wal.html), in order to allow concurrent database accesses.

This mode uses [two extra files](https://www.sqlite.org/walformat.html), one ending in `-wal`, and another ending in `-shm`. Those files persist after a database connection is closed. This is normal SQLite operation.

**Comment by groue** [comment] 2018-09-25 06:46
The [SQLite doc](https://www.sqlite.org/walformat.html) says:

> If the last client using the database shuts down cleanly by calling [sqlite3_close()](https://www.sqlite.org/c3ref/close.html), then [...] both the shm file and the wal file are unlinked. Thus, when the database is not in use by any client, it is usually the case that only the main database file exists on disk.

I do not witness this behavior (at least on macOS 10.14). Creating a DatabasePool instance builds the three database files (main, wal, she). Releasing the pool does perform a clean shut down, but the extra files are still on disk. Connection is not closed with sqlite3_close(), but with its newer version [sqlite3_close_v2()](https://www.sqlite.org/c3ref/close.html) which is supposed to bring improvements in, not regressions.

Have we found a defect in SQLite documentation, or a bug in SQLite implementation? If so, it may be useful to report a bug on the [SQLite mailing list](http://mailinglists.sqlite.org/cgi-bin/mailman/listinfo/sqlite-users). What do you think?

**Comment by scottandrew** [comment] 2018-09-25 15:05
I think there is something wrong because it is not clean. Also when adding data the data is left behind in the WAL file. The app I'm building is prepopulating a database for our iOS app. I have to call `self.database.dbPool.checkpoint(.truncate)` before closing to flush the write ahead data. I think there is a flaw just not sure where.

**Comment by groue** [comment] 2018-09-25 17:09
> I think there is something wrong because it is not clean. Also when adding data the data is left behind in the WAL file.

I can hear you, but I can also see how subjective a word like "clean" is.

GRDB closes the connections it opens, and that can be described as "clean", too.

SQLite comes with a command-line tool that we can assume is "clean", because it comes right from the SQLite authors. Does it leave -wal and -shm files behind? Yes it does:

```
$ sqlite3 /tmp/test.db
SQLite version 3.24.0 2018-06-04 14:10:15
Enter ".help" for usage hints.
sqlite> PRAGMA journal_mode = WAL;
wal
sqlite> CREATE TABLE t(a);
sqlite> .exit
$ ls /tmp/test.db*
/tmp/test.db        /tmp/test.db-shm    /tmp/test.db-wal
```

As far as I can tell, GRDB is as "clean" as SQLite itself, which sounds pretty good to me.

> The app I'm building is prepopulating a database for our iOS app. I have to call self.database.dbPool.checkpoint(.truncate) before closing to flush the write ahead data.

So your application is able to raise the level of "clean" where it wants it to be. Good!

SQLite has a behavior, GRDB does not alter it, and you can go further if you want. I'm pretty satisfied with this state of affairs.

I can go further, and say that I'm positively reluctant to change GRDB in order to go beyond the simple connnection closing, and remove the -wal and -shm files on DatabasePool deallocation. The reasons are:

- this would add two gratuitous potential failure points: on the file system, and with eventual external connections to the database.
- as all I/O operations, this could take a noticeable time, which may bother some users.

> I think there is a flaw just not sure where.

I'm too surprised that the SQLite behavior does not match its documentation, as seen in my comment above.

You may want to post on the SQLite mailing list, which is the recommended way to report SQLite issues. You'll find many helpful people here. I'll be glad to hear back from you after that.

Meanwhile, I don't see anything yet that should be changed in GRDB.

**Closed as completed** 2018-09-25 17:25 UTC
Labels: question

**Comment by groue** [comment] 2018-09-25 17:28
Thank you very much, Scott 😄! Happy GRDB!
