### ISSUE TITLE
Cannot find 'strcmp' in scope

### ISSUE THREAD

**Issue by harufumigithub** [groue/GRDB.swift#1628] opened 2024-09-18 01:11 UTC
Update macOS version 15.0
Update Xcode version 16.0

### What did you do?

Nothing.  The code used to be compiled but after the updates, it no longer compiles 

### What did you expect to happen?

Compiles

### What happened instead?

Cannot find 'strcmp' in scope

### Environment

**GRDB flavor(s):** GRDB
**GRDB version:** 5, 6 all fails 
**Installation method:** SPM
**Xcode version:** 16.0
**Swift version:** 5
**Platform(s) running GRDB:** iOS
**macOS version running Xcode:** 15.0

### Demo Project

Any spm samples available online

**Comment by groue** [comment] 2024-09-18 04:01
Duplicate of #1588. Upgrade to the latest version.

**Closed by groue** 2024-09-18 04:01 UTC
