### ISSUE TITLE
Crash RangeReplaceableCollection.append<A>(contentsOf:)

### ISSUE THREAD

**Issue by bgoncal** [groue/GRDB.swift#1626] opened 2024-09-16 09:53 UTC
### What did you do?

I have a logic that every time I receive updates from an API I check if I need to replace the information from my local database which uses GRDB, for that I do something like this:

```
let cachedEntities: [HAAppEntity] = try Current.database().read { db in
      try HAAppEntity
          .filter(Column(DatabaseTables.AppEntity.serverId.rawValue) == server.identifier.rawValue)
          .orderByPrimaryKey()
          .fetchAll(db)
  }
```

But sometimes this makes the App crash in background (This logic also runs in background), in Xcode crashes I see crash "RangeReplaceableCollection.append<A>(contentsOf:)".

### What did you expect to happen?

No crash

### What happened instead?

Crash

### Environment

**GRDB flavor(s):** GRDB
**GRDB version:** v6.29.3
**Installation method:** CocoaPods
**Xcode version:** 16 RC
**Swift version:** 5.7
**Platform(s) running GRDB:** iOS, macOS and watchOS
**macOS version running Xcode:** 15.1 Beta 3

### Demo Project

I don't have a demo project but the code fo my app is open source, the exact file I mentioned above is:
https://github.com/home-assistant/iOS/blob/master/Sources/App/AppEntitiesObserver.swift

Crash is pointed to be on line 52

![CleanShot 2024-09-16 at 11 45 55@2x](https://github.com/user-attachments/assets/63a2e28d-057c-4bc8-8c74-d5328a470ab4)
![CleanShot 2024-09-16 at 11 46 46@2x](https://github.com/user-attachments/assets/faa54ae2-87fd-40f9-a1ad-205bab275971)
![CleanShot 2024-09-16 at 11 46 54@2x](https://github.com/user-attachments/assets/2e6e6f57-9b3c-481f-935b-e59b05f84c59)

**Comment by groue** [comment] 2024-09-16 11:32
Hello @bgoncal,

Thank you for the report.

The crash report mentions `swift_getAssociatedTypeWitness`, which makes me think of another crash (#1619) which is due to a compiler bug regarding witness tables (see this [mastodon post](https://mastodon.sdf.org/@mikeash/113136475433234842)). You also mention Xcode 16 RC, which is another element in favor of this hypothesis.

May I ask if this crash has started happening after _some change_ in your app, or in the way the app is built or distributed? When you compare the version that crashes and the version that does not, was has changed?

**Comment by bgoncal** [comment] 2024-09-16 11:36
Unfortunately I just added GRDB to the App, so I don't have a previous version to compare :/
Yes the app was built with Xcode 16 RC

Minimum app version is iOS 15, crash happens (at least) on iOS 17.6 and 18

**Comment by bgoncal** [comment] 2024-09-16 11:37
Ive never seen the issue happening in foreground, so.. perhaps it has some relation? (Even though it would be something different from what you shared above).
I just added a check to only run it in foreground to see if the issue still happens or not

**Comment by groue** [comment] 2024-09-16 12:31
Thank you for the feedback.

> Unfortunately I just added GRDB to the App, so I don't have a previous version to compare

Welcome to the GRDB users :-)

> Minimum app version is iOS 15, crash happens (at least) on iOS 17.6 and 18

OK, so that's not #1619.

> Ive never seen the issue happening in foreground, so.. perhaps it has some relation? (Even though it would be something different from what you shared above).

Eventual background errors due to [data protection](https://developer.apple.com/documentation/uikit/protecting_the_user_s_privacy/encrypting_your_app_s_files) should turn into a runtime error that you can catch, not a hard crash (unless you use `try!`, of course). Quoting [the doc](https://swiftpackageindex.com/groue/grdb.swift/documentation/grdb/databaseconnections):

> When a database is protected, an application that runs in the background on a locked device won’t be able to read or write from it. Instead, it will catch [DatabaseError](https://swiftpackageindex.com/groue/grdb.swift/documentation/grdb/databaseerror) with code [SQLITE_IOERR](https://www.sqlite.org/rescode.html#ioerr) (10) “disk I/O error”, or [SQLITE_AUTH](https://www.sqlite.org/rescode.html#auth) (23) “not authorized”.

> I just added a check to only run it in foreground to see if the issue still happens or not

Why not: this could help narrowing the problem.

Did you try to trigger the crash on your own device?

---

As a temporary conclusion... Did you consider using Xcode 15.4, since Xcode 16 RC still has rough edges?

**Comment by groue** [comment] 2024-09-16 13:08
> I cannot use 15.4 because my app has iOS 18 specific features :/

Of course!

> I couldn't reproduce the issue while debugging, but I see it happening in the testflight version on my personal device.

It would be interesting to get a full crash log stored on the device, if possible. I would also run the app, from Xcode, in Release configuration. Attach the Xcode debugger to the TestFlight build could be interesting as well.

I'm sorry if I'm throwing ideas in the air, but I'm just as clueless as you are 😅

**Comment by bgoncal** [comment] 2024-09-16 13:18
No worries, ask for as much as you need haha, let me check the full log report and egt back to you

**Comment by bgoncal** [comment] 2024-09-17 22:01
After I added the checked for foreground the crash stopped happening, maybe too soon to tell but definitely an improvement

**Comment by groue** [comment] 2024-09-20 07:33
I assume this is yet another Xcode 16 bugs. I'm closing the issue. Please file a feedback at https://feedbackassistant.apple.com and to report the feedback number here.

**Closed** 2024-09-20 07:33 UTC

**Comment by groue** [comment] 2025-01-30 07:05
@bgoncal,

Thanks for the attached file. All the crashes show `0xdead10cc` as the "termination reason".

This is an exception that the OS throws to apps that share their SQLite file between several processes (such as an app and its extensions). See [Apple documentation](https://developer.apple.com/documentation/xcode/sigkill): "The operating system terminated the app because it held on to a file lock or SQLite database lock during suspension."

Oh, boy. Preventing 0xDEAD10CC is **very hard**. It's not a GRDB issue. It's a general issue with SQLite on Apple systems, which also plagues Core Data, SwiftData, etc.

At least GRDB has some docs about it: please check the entirety of [Sharing a Database ](https://swiftpackageindex.com/groue/grdb.swift/documentation/grdb/databasesharing) in the GRDB documentation (prefer the [version for GRDB 6](https://swiftpackageindex.com/groue/GRDB.swift/v6.29.3/documentation/grdb) if you haven't upgraded to GRDB 7 yet).

The best advice I can give is to **stop sharing the database file.** If you can design a communication system that goes through plain files, just go straight to it *right now*. You'll avoid much pain.

**Comment by bgoncal** [comment] 2025-01-30 08:36
@groue Oh I updated to GRDB 7 yesterday, should I rollback?

... I started reading the docs and the discussion in Apple forums and I could feel your frustration as well haha.
So besides the experimental approach of suspending the database, what else can I change on my structure to avoid this? 

Should I separate database into different files for different purposes? You mention plain files, but depending the situation this would be very painful to query.

In the last crash that I shared you can see "ClientEvent", this is an object used in the app so the user can later open a list of events that happened and search/filter etc, this kind of need to be available everywhere because an event can happen in multiple process.

Regarding the suspension approach, I guess I would need to create a mechanism that when the suspension is released I then write the ones that were not able to be written during suspension right?

And just double checking, this only applies for "write" operations, not "read", correct?

Thanks a lot for helping me out with that!

**Comment by groue** [comment] 2025-01-30 09:14
> Oh I updated to GRDB 7 yesterday, should I rollback?

GRDB 7 did not introduce any issue as far as I can say, and it is the way forward.

> So besides the experimental approach of suspending the database, what else can I change on my structure to avoid this?

Anything you can that makes sure a process does not hold a writer lock on the SQLite database when it becomes suspended. 🤷‍♂ 

GRDB suspension is a _possible_ solution for avoiding those locks. It's the only ready-made solution I can offer. I very much welcome further experimentations. *The problem is hard, and very time consuming*.

> And just double checking, this only applies for "write" operations, not "read", correct?

Yes.

What's important to understand is that `0xdead10cc` is a _correct_ handling of the situation. When an app becomes suspended while holding such a lock, other processes will fail accessing the database. The only way out is to kill the faulty process and to remove the lock. Only then other processes can proceed. That's what the OS does when `0xdead10cc` is raised (pronounced "dead lock").

A reading lock on a WAL database does not prevent other processes from accessing the database, and do not trigger `0xdead10cc`.

> [...] an event can happen in multiple process.

You're in the unfortunate situation where multiple processes want to write in the same database.



Maybe you can still avoid database sharing by having one database per process, which is not stored in a shared location, and design a synchronization protocol.

**Comment by bgoncal** [comment] 2025-01-30 09:30
Ok so to avoid complications I moved the logic to now save client events (since that until now they are the only one causing crashes) as a json file instead of GRDB database. This should be fine right

Check `Sources/Shared/ClientEvents/Model/ClientEventStore.swift` on https://github.com/home-assistant/iOS/pull/3378/files#diff-c55152765428fdf4ce1cea53ce3451a47075ee1b105362eff5770f6e695e60e9

**Comment by groue** [comment] 2025-01-30 14:05
I think this is the correct decision. I'm glad it did not require too much work (much less than avoiding `0xdead10cc` anyway).
