### ISSUE TITLE
accessing db on external volume fails

### ISSUE THREAD

**Issue by jelemans** [groue/GRDB.swift#1586] opened 2024-08-02 22:58 UTC
### What did you do?

I have an app which stores a db on a local drive which has been working for a long time.
However my database has gotten too big for the Mac it's on so I moved it to an external drive.

### What did you expect to happen?

The app would open and run as usual.

### What happened instead?

info : 16:44 : open/create db failed. error=SQLite error 14: unable to open database file

fwiw; I did a quick test project with 
https://github.com/stephencelis/SQLite.swift.git
and it opens the db on the external drive without trouble.

I also tested with 3 different external drives. I checked permissions with term and I set "Full Disk Access" on for the app. I tried both in the debugger and compiled apps. Sandboxing is off. 

### Environment

**GRDB flavor(s):** GRDB
**GRDB version: 16.28.0
**Installation method:** package manager
**Xcode version: tested on 15.2 and 16.0 beta 4
**Swift version:** 5
**Platform(s) running GRDB:**  macOS
**macOS version running Xcode:** tested on 14.5 and 15.0

**Comment by groue** [comment] 2024-08-04 05:40
Hello @jelemans,

I don't know the cause of this [SQLITE_CANT_OPEN](https://www.sqlite.org/rescode.html#cantopen) error. Take care of copying the database file as well along with its eventual companion [temporary files](https://www.sqlite.org/tempfiles.html), if they exist.

> fwiw; I did a quick test project with
> https://github.com/stephencelis/SQLite.swift.git
> and it opens the db on the external drive without trouble.

Interesting! Both libraries open the same [SQLite function](https://www.sqlite.org/c3ref/open.html) for opening the database. You may better understand what's wrong by comparing the exact options used by both GRDB and SQLite.swift.

**Comment by groue** [comment] 2024-08-22 07:18
No news is good news. I'm closing this issue.

**Closed by groue** 2024-08-22 07:18 UTC
Labels: support
