### ISSUE TITLE
deleteAll without filter: FetchedRecordsController's trackChanges not called

### ISSUE THREAD

**Issue by comaxime** [groue/GRDB.swift#156] opened 2016-12-18 11:17 UTC
When performing: 
`Record.deleteAll(db)`
the associated FetchedRecordsController does not notify of the changes (trackChanges not triggered)

but when performing:
`Record.filter(1 == 1).deleteAll(db)`
it does :)

**Comment by groue** [comment] 2016-12-18 13:57
Hello!

It looks like you've being bitten by the [truncate optimization](https://www.sqlite.org/lang_delete.html#truncateopt) which GRDB is supposed to handle correctly since v0.85.0. And indeed I can't reproduce your issue: I wonder whether you are using the latest GRDB version.

**Comment by comaxime** [comment] 2016-12-18 14:31
Thanks for the fast answer!
Am actually using GRDB.swift v0.98.0 (Xcode 8.2, simulator iPad Air 2 iOS 10.2, fresh install)

`    func clearAll() {
       databasePool.write { db in
            try? Record.deleteAll(db)
        }
    }`

Any more details I could provide?

**Comment by groue** [comment] 2016-12-18 15:15
OK, looks like you have found a real bug! Good thing you have a workaround until it is fixed.

Yes you can help, because I'm clueless: would you mind sharing some code, so that I can eventually reproduce the problem? Something like:

```swift
let controller = try FetchedRecordsController(dbPool, ...) // or dbQueue
controller.track { ... }
try controller.performFetch()

try dbPool.write { db in
    try Record.deleteAll(db)
}

// wait for changes that never come :'(
```

**Comment by comaxime** [comment] 2016-12-18 16:40
I have tested with this attached file:
[TestDeleteAll.swift.zip](https://github.com/groue/GRDB.swift/files/659521/TestDeleteAll.swift.zip)

A fetched records controller is tracking the changes:
1- Insert 3 records, filter(1==1).deleteAll, the fetched records controller prints the changes
2- Insert 3 records, deleteAll, the fetched records controller does not print anything

Here is what gets printed:
`Delete all records with filter(1 == 1).deleteAll(db)`
`RecordsDidChange triggered: number of records = 0`

then, after inserting again 3 records:
`Delete all records with deleteAll(db)`

recordsDidChange is not triggered

**Comment by groue** [comment] 2016-12-18 17:23
OK Maxime, I can reproduce the bug. Thanks for the report!

**Comment by comaxime** [comment] 2016-12-19 03:26
OK, let me know if I can help any further (but I fear this is now beyond my competencies ;) )

**Comment by groue** [comment] 2016-12-19 06:36
So far it's beyond mine as well ;-)

**Comment by groue** [comment] 2016-12-19 07:28
@comaxime OK the bug is found! A fixed release will ship shortly.

**Comment by comaxime** [comment] 2016-12-19 08:19
Great, thanks.
Where was the bug hiding?

**Comment by groue** [comment] 2016-12-19 08:49
The bug lies [here](https://github.com/groue/GRDB.swift/blob/v0.98.0/GRDB/Core/Database.swift#L1367) in the StatementCompilationObserver type which tells GRDB what is happening to the database.

According to https://www.sqlite.org/lang_delete.html#truncateopt:

> When the WHERE is omitted from a DELETE statement and the table being deleted has no triggers, SQLite uses an optimization to erase the entire table content without having to visit each row of the table individually.

This is what hides deletions from transaction observers.

> The truncate optimization can also be disabled at runtime using the sqlite3_set_authorizer() interface. If an authorizer callback returns SQLITE_IGNORE for an SQLITE_DELETE action code, then the DELETE operation will proceed but the truncate optimization will be bypassed and rows will be deleted one by one.

The fix will be to return SQLITE_IGNORE for SQLITE_DELETE [there](https://github.com/groue/GRDB.swift/blob/v0.98.0/GRDB/Core/Database.swift#L1349-L1351), and to write robust tests!

**Comment by groue** [comment] 2016-12-20 05:23
@comaxime GRDB v0.99.0 is out ([changelog](https://github.com/groue/GRDB.swift/blob/master/CHANGELOG.md#0990)). Thanks for the report!

**Comment by comaxime** [comment] 2016-12-20 05:33
Thanks @groue for the fast action!

**Comment by comaxime** [comment] 2016-12-20 13:37
@groue have just tried v0.99.0, I still have the issue ;)

**Comment by groue** [comment] 2016-12-20 13:46
Looks like I missed something…

**Comment by egrimmius** [comment] 2016-12-20 14:20
I don't know if this is an unintended consequence of the fix for this issue, but this new error I just received with version 0.99 seems to be related.  This is within DatabaseMigrator's registerMigrationWithDisabledForeignKeyChecks.  Here's the output:

INSERT INTO table_New SELECT * FROM oldTable
DROP TABLE "oldTable"
ROLLBACK TRANSACTION
error occurred in grdb: SQLite error 1 with statement `ALTER TABLE "table_New" RENAME TO "oldTable"`: there is already another table or index with this name: oldTable

This same code was working fine with version 0.97.

**Comment by groue** [comment] 2016-12-20 15:02
@egrimmius: your issue is unrelated. Please enable [SQL tracing](https://github.com/groue/GRDB.swift#databasequeue-configuration), look at the executed SQL, and if something still looks odd to you, open a [new issue](http://github.com/groue/GRDB.swift/issues).

**Comment by groue** [comment] 2016-12-20 17:37
@comaxime I'm dazzled. But not defeated yet!

**Comment by groue** [comment] 2016-12-20 18:24
@comaxime SQLite is full of traps, but I think I tackled it this time: I can run your test file and get all needed notifications:

```
Insert 3 records
RecordsDidChange triggered: number of records = 3

Delete all records with filter(1 == 1).deleteAll(db)
RecordsDidChange triggered: number of records = 0

Insert 3 records
RecordsDidChange triggered: number of records = 3

Delete all records with deleteAll(db)
RecordsDidChange triggered: number of records = 0
```

Is it possible for you to run your app with commit https://github.com/groue/GRDB.swift/commit/000f1d02c3bf7ed8c46fa25c153d67ba3d9b3738 ? This would prevent me from shipping a half-baked release this time. If not, I'll release a 0.99.1 version, hoping for the best.

When testing, make sure that the fetched records controller is kept alive: as soon as it is deallocated, it stops observing transactions, and may miss the last database update. So keep your instance of `TestDeleteAll` safe somewhere.

**Closed** 2016-12-21 04:44 UTC
Labels: bug

**Comment by groue** [comment] 2016-12-21 05:09
@comaxime Version 0.99.1 has shipped.

**Comment by comaxime** [comment] 2016-12-28 17:12
Thanks @groue, indeed I confirm this is fixed :)
