### ISSUE TITLE
Unexplained background crash that _might_ be related to GRDB

### ISSUE THREAD

**Issue by freak4pc** [groue/GRDB.swift#1085] opened 2021-10-21 21:17 UTC
### What did you do?

We noticed a few unexplained crashes on AppStore Connect that seem to happen while a user is in the background. The crashing thread isn't pointing to GRDB specifically, but GRDB-related code can be seen in Thread 2 of the crash log (attached), and since we've added it relatively recently, it draws a bit of sense to suspect it.

[crash_report.txt](https://github.com/groue/GRDB.swift/files/7392846/crash_report.txt)
(Some of the symbols have been starred-out for obfuscation)

The part with `upsertEntity` in the stack trace has code that looks similar to the following

```swift
database.asyncWrite(
    work: { db in 
        try Entity.updateAll(db, Entity.Column.recencyIndex.set(to: nil))

        for recent in recents {
            try recent.upsertEntity(db) // -> Trace highlights this line
        }
    },
    completion: { result in ... }
)
```

And `upsertEntity` itself looks like this:

```swift
extension Entity {
    func upsertEntity(_ db: GRDB.Database) throws {
        guard let localEntity = try Entity.fetchOne(db, ...) else {
            try insert(db)
            return
        }

        let updatedEntity = Entity(
            ... // Updated model modeled after `localEntity` with some modified values
        )

        try updatedEntity.update(db)
    }
}
```

### What did you expect to happen?

No crashes while user is in background

### What happened instead?

A background crash that isn't necessarily directly related to GRDB, but does have it "near the surface" and close to the crashing thread. I've also specifically wanted to share some of the code above to see if there's anything "fishy" that pops to your eyes that could cause it.

I did suspect Data Protection, but even if that was the cast, I'd expect it to just throw an error (catched by the `asyncWrite`) and not crash the app.

### Environment

**GRDB flavor(s):** GRDB
**GRDB version:** 5.10
**Installation method:** CocoaPods
**Xcode version:** 13.0
**Swift version:** 5.5
**Platform(s) running GRDB:** iOS
**macOS version running Xcode:** 11.6

### Demo Project

Unfortunately can't share an actual project and also can't directly "repro" this. I've shared the crash log and relevant code portions above, which I hope can help a bit with figuring this out.

**Comment by freak4pc** [comment] 2021-10-29 20:18
Hey @groue - we're still seeing these crashes but it's all users in different countries, so we don't have access to their physical device (and definitely not in the immediacy needed to get a console dump). 

I'm not entirely sure what to do. I guess we can close this and wait to see if I can get any new findings later on.

**Comment by groue** [comment] 2021-10-29 21:14
OK, let's close this. Feel free to report any finding, in case it could help other users 👍

**Comment by freak4pc** [comment] 2022-01-20 21:38
P.S. As you see this _isn't_ the same crash as the original, but it seems similar (at least from the EXC_CRASH (SIGKILL) EXC_CORPSE_NOTIFY exception angle). If I have any more thoughts on that original crash I'll share those as well.

**Comment by groue** [comment] 2022-01-21 07:23
Thanks for the update, @freak4pc

So it looks like a deadlock. Which GRDB version are you using?

**Comment by freak4pc** [comment] 2022-01-21 07:36
Thanks, we're on 5.15

**Comment by groue** [comment] 2022-01-21 08:18
> Thanks, we're on 5.15

OK. `ValueObserver.notifyChanges` does indeed use an NSRecursiveLock, and this may be the one that is deadlocked. It may also be a lock owned by your app, but let's suppose it's the GRDB one.

I hope your crash log contains the stack trace of all of your application threads. Can you notice other threads that are using GRDB?

**Comment by freak4pc** [comment] 2022-01-21 13:08
Here's the full symbolicated log:

[2022-01-20_22-29-24.6190_+0200-4788e7062cae210b2b52bc1e4f77d4dc2dafcec8.txt](https://github.com/groue/GRDB.swift/files/7913810/2022-01-20_22-29-24.6190_%2B0200-4788e7062cae210b2b52bc1e4f77d4dc2dafcec8.txt)

I see that there's some of our code in between the GRDB, related code - which makes me think it's some conflict we're not aware of? 


<img width="1190" alt="image" src="https://user-images.githubusercontent.com/605076/150532003-44e30b93-2194-4ac1-81b3-d5859b3c9461.png">
 
`UsersProvider.users(sql:)` looks like this (`database.rx.observe` is a simple RxSwift wrapper that uses ValueObservation):

```swift
func users(sql: String? = nil) -> Observable<[UserModel]> {
    database.rx.observe { db in
        var query = UserModel
            .filter(UserModel.Column.isDisabled == false)
        if let sql = sql, !sql.isEmpty {
            query = query.filter(sql: sql)
        }
        return try query
            .order(UserModel.Column.name.asc)
            .fetchAll(db)
    }
}
```

**Comment by freak4pc** [comment] 2022-01-21 15:53
Sorry for another separate reply here, just wanted to share another crash report where GRDB isn't on the main thread, but it's still in that same "writer queue" with monday stuff in between some GRDB operations.

The similarity is there, I'm wondering if it's somehow related. Perhaps I'm doing something I'm not supposed to, even though I'm always performing work inside transactions, etc. 

Here it is:
[crash2.txt](https://github.com/groue/GRDB.swift/files/7914951/crash2.txt)

**Comment by groue** [comment] 2022-01-22 07:57
Focusing on the first crashlog, I don't understand why the main thread appears locked as it tries to notify a database change to your app. The second thread that involves GRDB is starting a new observation (and is not waiting).

May I ask how your application is using value observations? How frequently are they started? What is your app doing when fresh database values are notified? Does it happen that observations feed themselves? For example, are observations started from change notifications? Is the database modified as a result of change notifications? Anything that looks "fancy" in any way (please have a low threshold for "fancy")?

**Comment by freak4pc** [comment] 2022-01-22 08:16
We are using them pretty frequently in some places in the app. We have about 13 instances of them throughout the app. 

Since the observations are wrapped in an `Observable` it might be a bit tricky tracking down what consumers might be writing to the database, but those are (should) still be isolated. 

Two big things that I think could be related:
1. We have a relatively big insert/upsert close to the start of the app, about 20k records possibly for a large user. There are different areas in the app observing changes to that table (last 200 items, but still the table as a whole). not sure if this is related and it seems like a valid case? 
2. We have another area that stores a list of users using `asyncWrite`, and a different area observing them. Still, don't think this is too fancy ...

Is there any thing invalid with doing a separate write transaction inside a value observation? I don't think we have this case but you did mention it as an option.

**Comment by groue** [comment] 2022-01-22 09:21
Nothing really rings any bell to me.

> Is there any thing invalid with doing a separate write transaction inside a value observation?

No, it is not invalid. I was looking for anything that could have been overlooked.

**Comment by freak4pc** [comment] 2022-01-22 20:56
Is there any additional information I could try and debug around this? 
I'm happy to try anything... I could share all 13 ValueObservations in the app but I'm not sure it'd actually help :)

**Comment by groue** [comment] 2022-01-22 21:02
I really don't know, @freak4pc... You're at the the best position for reducing and reproducing, I'm afraid. I'd love to help but I'm no wizard.

**Comment by freak4pc** [comment] 2022-01-22 21:03
Sure, I agree, but the crash in the original message does seem to revolve around locking inside GRDB so I thought you might have some thoughts (of course I didn't think you're any wizard ;-) ). I'll try to keep poking at this. Thanks.

**Comment by groue** [comment] 2022-01-22 21:07
Sure. I'll leave the issue open for a while.

**Comment by freak4pc** [comment] 2022-01-23 12:51
Two updated on this:

1. We've started filtering emissions from ValueObservations while the app is in the background - this seems to help with the crashes (we'll monitor)

2. We noticed the app talks about a UIBackgroundTask not being completed in the expiration threshold in the background (`Background task still not ended after expiration handlers were called`). The relevant background task is [most likely here](https://github.com/groue/GRDB.swift/blob/master/GRDB/Core/DatabasePool.swift#L214-L224). Could you share a bit what `releaseMemory` does? Is there anything that could cause it to halt? Might help me further debug on our end?

https://github.com/groue/GRDB.swift/blob/master/GRDB/Core/DatabasePool.swift#L214-L224

Thanks!

**Comment by groue** [comment] 2022-01-23 14:09
> Could you share a bit what releaseMemory does? 

Sure:

- https://github.com/groue/GRDB.swift/blob/v5.15.0/GRDB/Core/DatabasePool.swift#L171-L178
- https://github.com/groue/GRDB.swift/blob/v5.15.0/GRDB/Core/Database.swift#L1199-L1204

> Is there anything that could cause it to halt? Might help me further debug on our end?

`DatabasePool.releaseMemory` calls [`Pool.barrier`](https://github.com/groue/GRDB.swift/blob/v5.15.0/GRDB/Utils/Pool.swift#L126), and waits until all current reads are completed.

**Comment by groue** [comment] 2022-01-24 07:59
> `DatabasePool.releaseMemory` calls [`Pool.barrier`](https://github.com/groue/GRDB.swift/blob/v5.15.0/GRDB/Utils/Pool.swift#L126), and waits until all current reads are completed (so that it can close all reader connections).

More precisely, it waits until no one is waiting for a read access. It then closes all reader connections.

**Comment by groue** [comment] 2022-02-15 19:36
I'm not sure it is useful to keep this issue opened, since no progress is done. Let's wait for more actionable input!

**Closed by groue** 2022-02-15 19:36 UTC
Labels: help wanted, support
