### ISSUE TITLE
Unable to infer closure type in the current context FetchedRecordsController.swift

### ISSUE THREAD

**Issue by scarer** [groue/GRDB.swift#261] opened 2017-10-09 20:58 UTC
let itemsAreIdenticalFactory: ItemComparatorFactory<Record>
        if let isSameRecord = isSameRecord {
            itemsAreIdenticalFactory = { _ in { isSameRecord($0.record, $1.record) } }
        } else {
            itemsAreIdenticalFactory = { _ in { _ in false } }
        }

**Comment by groue** [comment] 2017-10-09 21:06
What is your question?

**Comment by scarer** [comment] 2017-10-09 21:19
The code has an issue and won’t build for the latest XCode - GRDB.swift-master/GRDB/Record/FetchedRecordsController.swift:88:47: Unable to infer closure type in the current context
 
        let itemsAreIdenticalFactory: ItemComparatorFactory<Record>
        if let isSameRecord = isSameRecord {
            itemsAreIdenticalFactory = { _ in { isSameRecord($0.record, $1.record) } }
        } else {
            itemsAreIdenticalFactory = { _ in { _ in false } }
        }

**Comment by groue** [comment] 2017-10-10 04:03
I'm sorry but this code builds everyday, without any error, on many setups that conform to the requirements listed at the top of the project's README.

Please **take the time** to provide a proper problem report.

**Comment by groue** [comment] 2017-10-13 10:13
My little finger tells me you won't reply or close this issue. No news is good news: happy GRDB!

**Closed by groue** 2017-10-13 10:13 UTC
Labels: support

**Comment by yogendrakarekar** [comment] 2017-11-16 13:51
Hi I found the same issue, the issue is that when we install GRDB through cocoa pod, and then when we try building the application, the build shows error in FetchedRecordsController of grdb. Kindly help us fixing it.
I am using xcode 9 and swift 3

**Comment by groue** [comment] 2017-11-16 14:05
Hello @yogendrakarekar.

I'll make the same answer as I did to @scarer: many users, including me, build GRBD through CocoaPods almost daily. And this issue does not happen. So if you want help, please **take the time** to write a proper problem report. And start by checking the GRDB requirements at the top of the readme file. Thanks.

**Comment by scarer** [comment] 2017-11-16 16:11
Try downloading and re-importing the latest code build, updating cocoa pods, cleaning your project and restarting xcode.

Also, make sure you refresh your frameworks in your build settings.

I didn’t want to leave up an answer as the maintainer seemed angry. 

Hope that helps.

Thanks,

Sarah

**Comment by Kirow** [comment] 2017-11-16 16:54
tried myself on new clean project - everything works fine. Better if you will create sample project where it will be possible to reproduce this issue.

**Comment by groue** [comment] 2017-11-16 17:10
Thanks for the feedback, @scarer. It may help other users.

Now I wasn't angry. When someones opens an issue without any clear question or context, despite my request for details, what can I do? An issue that contains no usable information for other users or for contributors has no value.

**Comment by groue** [comment] 2017-11-16 17:29
Hints when a contributor asks for details: **Provide details.**

This includes:

- the version of Xcode, and if other version of Xcode are installed on the computer
- the flavor of GRBD installed (GRDB, GRDBCipher, GRDBCustom?)
- the version of GRBD installed (v2.3.1, other?)
- the installation method (CocoaPods, SPM, Carthage, Manual?)
- a sign that you have read the requirements and searched the doc for an answer to your question
- a clear and precise statement of your issue

The list is long. But it can fit in two sentences. For example:

> Hello, I've installed GRDB v2.3.1 in Xcode 9.1 with CocoaPods. When I do *foo*, I get *bar* instead of *baz*, despite *this piece of documentation*.

I guess I'll have to write an issue template some day. Fortunately, I currently don't have to close too many issues as [invalid](https://github.com/groue/GRDB.swift/issues?q=is%3Aissue+is%3Aclosed+label%3Ainvalid) because of their low quality.

**Comment by anisimovyuriy** [comment] 2018-05-15 14:36
Wow @groue,

Didn't expect such responses as you posted and then giving some hint after. You should work with you attitude pal!

Cheers!

**Comment by groue** [comment] 2018-05-19 12:18
A disrespectful comment has been deleted, and this issue is now locked: it has attracted too many low-quality contributions, and will not bring any useful information to anybody.
