### ISSUE TITLE
SPM dynamic library?

### ISSUE THREAD

**Issue by simme** [groue/GRDB.swift#596] opened 2019-08-19 10:44 UTC
Hey,

This might be a stupid question and I realize some of the involved technologies are still in beta and in other ways not "done". And perhaps this has nothing to do with GRDB.

Currently, when using GRDB via SPM in Xcode 11, what you get is a static library. This poses a few issues due to libraries being compiled as static by default.

1. It becomes weird to use GRDB in more than one target, ex two frameworks. Partly because as far as I understand it static libraries are embedded in each target. Hence you end up with multiple copies of GRDB in your app which increases binary size and also yields errors like this:
> objc[10333]: Class _TtC4GRDB8Database is implemented in both /Users/simme/Library/Developer/Xcode/DerivedData/... (0x10dc4d4f8) and /Users/simme/Library/Developer/Xcode/DerivedData/... (0x10cfa6a10). One of the two will be used. Which one is undefined.

2. It seems like frameworks with static libraries can't be used in Playgrounds. I haven't done any extensive research on this topic in particular, but I've been able to import frameworks using GRDB before I switched to using SPM.

I'm a solo dev so I can work around these issues fairly easily by just going back to using git submodules. But SPM does provide a bit less of a maintenance burden and feels nicer. From what I can tell it is possible to provide dynamic targets in Swift packages by specifying them as such in the Package.swift-file. But I know too little about the difference and implications to know if this is "good" or "bad".

Anyway, I just wanted to raise the issue to see if there's anything that can be done from the GRDB side to alleviate these issues by providing different configurations.

**Comment by groue** [comment] 2019-08-19 11:18
Hello @simme,

I don't know SPM and Xcode 11 enough to answer your questions. I'll leave the issue open for a few days, in case somebody has a some answer, or if you find some useful information to share. I'll close it afterwards, because this is not really a question about GRDB.

**Comment by simme** [comment] 2019-08-19 11:42
It sorta is if a "fix" can be provided via the Package-file.

I could try a fork of my own, adding `.library(name: "GRDBDynamic", type: .dynamic, targets: ["GRDB"]),` tot he Package file to see if it fixes any of the issues and report back. I don't know enough about the difference between static and dynamic libraries. But before SPM I always built GRDB as dynamic and never had these issues.

**Comment by groue** [comment] 2019-08-19 14:31
Re-reading your message, I think that the part quoted below is enough to open a [bug report](https://feedbackassistant.apple.com), for sure, and maybe ask a question in the [Swift Forums](https://forums.swift.org) or the [Apple Developer Forums](https://forums.developer.apple.com/welcome):

> It becomes weird to use GRDB in more than one target, ex two frameworks. Partly because as far as I understand it static libraries are embedded in each target. Hence you end up with multiple copies of GRDB in your app which increases binary size and also yields errors like this:
>
>>objc[10333]: Class _TtC4GRDB8Database is implemented in both /Users/simme/Library/Developer/Xcode/DerivedData/... (0x10dc4d4f8) and /Users/simme/Library/Developer/Xcode/DerivedData/... (0x10cfa6a10). One of the two will be used. Which one is undefined.

But the actual setup that triggers the problem is unclear. And I find the word "framework" in a context of static libraries is somewhat confusing. Maybe a short description would help the understanding.

**Comment by simme** [comment] 2019-08-19 19:21
It is not a bug. It's what happens when there are multiple instances of the same static library in an app. Which, afaik, can't be avoided when a dependency is compiled as a static library and two of my custom frameworks has that library as a dependency.

I'm working on a custom fork of GRDB that specifies a dynamic product in the Package.swift file. Will report back. My internet is terribly slow and it takes a while to fetch all of GRDB multiple times.. 😅

**Comment by simme** [comment] 2019-08-20 07:31
These conclusions are by no means exhaustive or definitive — but, from limited testing it seems like switching the targets to be dynamic can fix both of my issues. I haven't seen any ill effects.

Using my framework in the playground required me to explicitly import GRDB (something that couldn't be done when it was compiled as a static library). But that might just be something with my setup. And I cannot experiment further with framework settings because Xcode beta crashes when I do so. Downloading beta 6 as I write this.

**Comment by groue** [comment] 2019-08-27 08:04
OK, I guess it is time to close this issue. Don't hesitate re-opening it, or add more information, @simme. The title is quite googleable, should any other user get interested in the topic :-)

**Closed by groue** 2019-08-27 08:04 UTC

**Comment by gverdouw** [comment] 2020-06-17 08:50
I think this would help my use case. 

Currently I have a shared framework (actually a number of shared frameworks) (`SharedFramework`) which depends upon GRDB  and two apps using this framework, one of which supports iOS 11+ and the other supports iOS 13+. 

If I want to use `GRDBCombine` in the iOS 13 app I need to create a new `SharedFrameworkCombine` framework which has a dependency to `GRDBCombine`. However if I want to have the iOS 13 app depend on the `SharedFramework` and `SharedFrameworkCombine` I run in to issues where two copies of the GRDB static library are embedded into the app (from both frameworks). 

The iOS 11+ app continues to work perfectly through this, but the app wanting to use Combine becomes more and more troublesome as other shared frameworks depend on `SharedFramework` (so that when the iOS 13 app wants to use these other frameworks it needs to clone them to another framework which depends on `GRDBCombine` instead of `GRDB`).

Hopefully that description makes sense
