### ISSUE TITLE
Redifination of Module GRDB

### ISSUE THREAD

**Issue by mikgar26** [groue/GRDB.swift#1387] opened 2023-06-06 09:55 UTC
After adding GRDB via SPM to my project, if I compile from XCode I get the following error:

redefinition of module 'GRDB'

from console: 

The following build commands failed:
	SwiftGeneratePch normal arm64 Compiling\ bridging\ header (in target 'iOTA' from project 'iOTA')
(1 failure)
make: *** [build/Build/Products/Debug-iphoneos/iOTA.app] Error 65

Environment

GRDB flavor: GRDB
GRDB version: 6.15.0
Installation method: SPM
Xcode version: 14.2
Swift version: 5.7.2
Platform running GRDB: iOS
macOS version running Xcode: MacOS Monterey v. 12.6.3

**Comment by groue** [comment] 2023-06-06 10:38
Hello @mikgar26,

Many Xcode projects use GRDB with SPM without any error, so probably something is wrong in your setup. It's impossible to tell, considering the little information you have provided.

Did you try cleaning the build folder, and other classical Xcode cleanup actions (such as deleting the Derived Data folder)?

Did you look for the "redefinition of module" error on your favorite Internet search engine?

Please report the results of your investigations. And if you still think something is wrong with GRDB, a [reproductible example](https://stackoverflow.com/help/minimal-reproducible-example) would greatly help identifying the problem, thank you.

**Comment by mikgar26** [comment] 2023-06-06 11:35
Hi @groue,

yes I tried running a cleanup of the build folder and also the Derived Data. The problem is with the module.modulemap. The complete error is: 

redefinition of module GRDB previously defined here

Xcode finds two module.modulemaps defining the same package

**Comment by groue** [comment] 2023-06-06 11:37
Then it looks like your app has two versions of GRDB (probably one would be enough). Xcode is even kind enough to tell you _where_ is the other one (but you didn't tell, maybe because you didn't read the error message).

**Comment by mikgar26** [comment] 2023-06-06 11:42
redefinition gives it between the Support and SQLiteCustom folders.

**Comment by groue** [comment] 2023-06-06 12:17
Oh, this "SQLiteCustom" (whatever it is, since you didn't tell anything and don't look like you want to help yourself) is highly suspicious: when you install GRDB with SPM, GRDB wants to use the SQLite library that ships with the operating system. Using a custom version of SQLite at the same time will create a whole other world of problems.

**Comment by groue** [comment] 2023-06-06 13:22
All right. I'll leave the issue open a few days, so that you can find the time to investigate, and report your findings. This will help other users who meet the same problem. I can't do anything myself.

**Comment by mikgar26** [comment] 2023-06-06 13:58
I correctly performed the import as you described, but as you can see the compiler keeps giving me the same error

<img width="261" alt="Schermata 2023-06-06 alle 15 55 32" src="https://github.com/groue/GRDB.swift/assets/129089715/737c00d6-a2f5-49ca-932f-27e3b4d2bd58">

**Comment by groue** [comment] 2023-06-06 14:01
Well. I'll just repeat myself:

> I just created a new project with Xcode 14.2, a SwiftUI iOS app, added the GRDB SPM dependency, and successfully built the app.

> I'll leave the issue open a few days, so that you can find the time to investigate, and report your findings. This will help other users who meet the same problem. I can't do anything myself.

**Comment by mikgar26** [comment] 2023-06-07 09:41
I tried re-downloading the project from my personal git without the changes that contained the use of the GRDB api. I simply added the package and compiled and ran the project and this is the output from Xcode: 

`
{
  "kind": "finished",
  "name": "compile",
  "pid": 24648,
  "output": "\/Users\/Shared\/Files From c.localized\/Sviluppo\/ANTS_iOTA\/iOTAFromGitlab_22052023\/iOTA\/iOTA\/build\/SourcePackages\/checkouts\/GRDB.swift\/SQLiteCustom\/module.modulemap:1:18: error: redefinition of module 'GRDB'\nframework module GRDB {\n                 ^\n\/Users\/Shared\/Files From c.localized\/Sviluppo\/ANTS_iOTA\/iOTAFromGitlab_22052023\/iOTA\/iOTA\/build\/SourcePackages\/checkouts\/GRDB.swift\/Support\/module.modulemap:1:18: note: previously defined here\nframework module GRDB {\n                 ^\n\/Users\/Shared\/Files From c.localized\/Sviluppo\/ANTS_iOTA\/iOTAFromGitlab_22052023\/iOTA\/iOTA\/build\/SourcePackages\/checkouts\/GRDB.swift\/SQLiteCustom\/module.modulemap:1:18: error: redefinition of module 'GRDB'\nframework module GRDB {\n                 ^\n\/Users\/Shared\/Files From c.localized\/Sviluppo\/ANTS_iOTA\/iOTAFromGitlab_22052023\/iOTA\/iOTA\/build\/SourcePackages\/checkouts\/GRDB.swift\/Support\/module.modulemap:1:18: note: previously defined here\nframework module GRDB {\n                 ^\n<unknown>:0: error: could not build Objective-C module 'SwiftOverlayShims'\n",
  "process": {
    "real_pid": 24648
  },
  "exit-status": 1
}
`

**Comment by groue** [comment] 2023-06-07 09:55
Good! Now describe a detailed and complete procedure for reproducing the problem, and maybe someone will be able to help you. It looks like you did not understand yet that nobody can help with the little information you have provided so far. Please do adapt your understanding. And provide the requested detailed and complete procedure for reproducing the problem. Otherwise, I'll just close this issue right away because I've now lost too much time trying to make you understand how support works. Thank you.

**Comment by groue** [comment] 2023-06-11 10:55
I'm closing the issue. Feel free to reopen with a detailed procedure that reproduces the problem.

**Closed by groue** 2023-06-11 10:55 UTC
Labels: needs user input
