### ISSUE TITLE
App crashes with `EXC_BAD_ACCESS` on first database read in Xcode 16 Beta 6

### ISSUE THREAD

**Issue by SwiftedMind** [groue/GRDB.swift#1596] opened 2024-08-22 14:09 UTC
### What did you do?

I launched my app as usual, with the new Xcode 16.0 Beta 6 and the app crashed immediately at the first database read:

```swift
try AppDatabase.shared.dbWriter.read { _ in }
```

The error is a generic `Thread 1: EXC_BAD_ACCESS (code=1, address=0x28)` with no usefule stacktrace, unfortunately.

I assume this is an Xcode regression in the latest Beta, but I wanted to post it here just in case. Maybe it's also my database setup that's wrong and only now causes a problem? I'm not entirely sure 🤔

### Environment

**GRDB flavor(s):** GRDB
**GRDB version:** 6.29.1
**Installation method:** SPM
**Xcode version:** 16.0 Beta 6
**Swift version:** 5.10 (also happens with 6.0)
**Platform(s) running GRDB:** iOS (In a and also on a real device, iOS 18.0 Beta 7)
**macOS version running Xcode:** macOS 15 beta 7

### Demo Project

https://github.com/SwiftedMind/GRDBCrashDemo

This is a minimal example, I've tried deleting as much as possible. If you run the app, it immediately crashes.

**Comment by groue** [comment] 2024-08-24 09:13
Hello @SwiftedMind,

This looks like an Xcode regression indeed.

I could not detect the condition that creates this miscomputation. GRDB demo and test apps make liberal uses of `any DatabaseWriter`, and don't crash on Xcode 16.0 beta 6.

If you have time, please report the bug at http://feedbackassistant.apple.com.

**Comment by SwiftedMind** [comment] 2024-08-24 10:26
Thanks 🙂 

I've reported it: FB14907330

I'll wait for the next Beta and check again. Luckily, the crash does not happen on Xcode 16.1 Beta 1, so I'll just use that for now.

**Comment by groue** [comment] 2024-08-24 11:37
Thank you, @SwiftedMind 👍 

I'm closing the issue because there isn't anything that has to be done in this repository.

**Closed** 2024-08-24 11:37 UTC
