### ISSUE TITLE
Error when building in Xcode 10 beta

### ISSUE THREAD

**Issue by nijs9** [groue/GRDB.swift#383] opened 2018-07-09 07:36 UTC
### What did you do?

With a pod install, I use GRDB in my Swift 4.1 project and trying to build the project

### What did you expect to happen?

Build without error

### What happened instead?

When I build my project, I always get this error:

error: open /Users/user1/Library/Developer/Xcode/DerivedData/App4.0-cnufytypurlkbkdehiqdnpqyspvb/Build/Products/Debug-iphonesimulator/GRDB.swift/GRDB.framework/Headers/GRDB-Bridging.h: Permission denied

Deleting DerivedData folder doesn't fix this. The GRDB-Bridging.h file has only read permissions. When manually changing the permissions to write permission, next time I build permissions are overwritten to readonly again...

When using GRDB.swift 3.2 in Xcode 9, the problem doesn't occur...

### Environment

**GRDB flavor(s):** GRDB.swift
**GRDB version:** 3.2
**Installation method:** POD
**Xcode version:** 10 beta 3
**Swift version:** 4.1
**Platform(s) running GRDB:** iOS
**macOS version running Xcode:** High sierra

**Comment by emilpedersen** [comment] 2018-07-09 08:14
A quick fix I use is:
Put a comment in the GRDB-Bridging.h file in the pods folder.
`// WORKS`

**Comment by nijs9** [comment] 2018-07-09 08:17
@emilpedersen thanks. Can you describe this a fix a bit more specific please? Do you mean to add a command in this file? /Users/user1/Library/Developer/Xcode/DerivedData/Wandelknooppunt4.0-cnufytypurlkbkdehiqdnpqyspvb/Build/Products/Debug-iphonesimulator/GRDB.swift/GRDB.framework/Headers/GRDB-Bridging.h?

**Comment by emilpedersen** [comment] 2018-07-09 08:22
No inside your project folder you should have a Pods folder
Mine is:
`Users/emilpedersen/Documents/TimeToStand/Pods/GRDB.swift/Support/GRDB-Bridging.h`

**Comment by groue** [comment] 2018-07-09 10:02
Hello, please also see https://github.com/groue/GRDB.swift/issues/379

**Comment by groue** [comment] 2018-07-09 17:34
I'm closing this issue since it looks there is no issue any longer. Thanks, @emilpedersen, for chiming in!

**Comment by pascalscheffers** [comment] 2018-07-11 09:37
groue, the problem is not fixed. emilpedersen posted a work around. Until a comment is added to Support/GRDB-Bridging.h, it is not solved.

**Comment by groue** [comment] 2018-07-11 10:42
@pascalscheffers: adding a comment to Support/GRDB-Bridging.h is a *very weird* workaround. It is unlikely to be the final solution to this problem. And you'll see in #379 that Xcode 10 can give other bizarre symptoms.

You are all running **beta software**, and this has a meaning: you have chosen to use unfinished software that may contain bugs. You can't expect normal support. You can't expect issues to be solved for you. After all, where's the bug? In your setups? In GRDB? In CocoaPods? In Xcode? Who knows? I certainly don't. And I won't spend much time figuring out, unless I can quickly help, as in #379.

That's why I think that this weird workaround is *enough* today, and that the issue can be closed.

Yet you can be sure that when Xcode 10 ships for good, GRDB will be ready for good. Until then, you have to face the consequences of living in beta 🚧

**Comment by sobri909** [comment] 2018-07-11 10:48
> After all, where's the bug? In your setups? In GRDB? In CocoaPods? In Xcode? Who knows?

I think you answered that one yourself: "You are all running beta software". The bug appears to be in the beta software - in Xcode. 

The catch is we don't quite have a choice about it. Xcode 10 is here, and a lot of us have to work with it now, even if we would prefer not. 

> That's why I think that this weird workaround is enough today, and that the issue can be closed.

I agree that it's enough for now. The workaround fixes the problem, but it's also not a sensible piece of code, so committing it to the repo would be weird / wrong.

But the problem is still going to be hitting a whole bunch of devs, who will come looking for answers. 

With that in mind, it seems reasonable to keep the issue open until it's no longer a problem? At the very least it gives people an answer when they come looking, thus avoiding duplicate "bug" reports.

**Comment by groue** [comment] 2018-07-11 10:49
> With that in mind, it seems reasonable to keep the issue open until it's no longer a problem? At the very least it gives people an answer when they come looking, thus avoiding duplicate "bug" reports.

Sounds sensible 👍

**Comment by pascalscheffers** [comment] 2018-07-11 11:02
@groue cheers. Yeah, I totally agree it is a weird work around, but also harmless. The reality is we need to build in Xcode 10 so we can test on iOS 12. 

Cheers.

**Comment by groue** [comment] 2018-07-11 11:07
Yes. Sorry folks I have been slow.

**Comment by tapi** [comment] 2018-07-18 19:07
FWIW it looks like adding a comment and then saving it is just setting the permissions

**Comment by groue** [comment] 2018-09-05 17:35
GRDB 3.3.0-beta1 is out. It supports Xcode 10 beta 6 and Swift 4.2.

**Comment by groue** [comment] 2018-09-16 18:16
GRDB 3.3.0 is out, with support for Xcode 10 GM.

**Closed by groue** 2018-09-16 18:16 UTC
Labels: support
