### ISSUE TITLE
Swift 2.x: Memory leak when filtering with two conditions

### ISSUE THREAD

**Issue by craigzour** [groue/GRDB.swift#122] opened 2016-09-15 18:12 UTC
Hi,

I discovered a memory leak in your library when I was integrating it to my project. I hope you guys will be able to understand what is going on.

I created a small project on the side to make sure it was not related to the rest of my code and yeah, unfortunately, it was still there.

```swift
import UIKit
import GRDB

class DatabaseRecord: Record {
    
    static let topicIdColumn = SQLColumn("topicId")
    static let bucketIdColumn = SQLColumn("bucketId")
    static let payloadColumn = SQLColumn("payload")
    
    var topicId: String?
    var bucketId: Int64?
    var payload: NSData?
    
    init(topicId: String, bucketId: Int64, payload: NSData) {
        self.topicId = topicId
        self.bucketId = bucketId
        self.payload = payload
        super.init()
    }
    
    required init(_ row: Row) {
        self.topicId = row.value(DatabaseRecord.topicIdColumn)
        self.bucketId = row.value(DatabaseRecord.bucketIdColumn)
        self.payload = row.value(DatabaseRecord.payloadColumn)
        super.init()
    }
    
    override var persistentDictionary: [String: DatabaseValueConvertible?] {
        return [
            "topicId": self.topicId,
            "bucketId": self.bucketId,
            "payload": self.payload,
        ]
    }
    
    override class func databaseTableName() -> String {
        return "topics"
    }
    
}

class Database {
    
    let databaseQueue: DatabaseQueue
    
    var topicId: UInt64
    var bucketId: UInt64
    
    init() {
        let libraryDirectoryUrl = NSFileManager.defaultManager().URLsForDirectory(NSSearchPathDirectory.LibraryDirectory, inDomains: NSSearchPathDomainMask.UserDomainMask).first!
        
        let dbUrl = libraryDirectoryUrl.URLByAppendingPathComponent("topics.db")
        let dbPath = dbUrl.path!
        
        self.databaseQueue = try! DatabaseQueue(path: dbPath)
        
        self.topicId = 0
        self.bucketId = 0
        
        self.createTable()
        
        self.insertData()
    }
    
    func createTable() -> Void {
        self.databaseQueue.inDatabase { database in
            try! database.create(table: "topics", ifNotExists: true) { tableDefinition in
                tableDefinition.column("topicId", .Text)
                tableDefinition.column("bucketId", .Integer)
                tableDefinition.column("payload", .Blob)
                
                tableDefinition.primaryKey(["topicId", "bucketId"])
            }
        }
    }
    
    func insertData() -> Void {
        
        let data = "my sentence".dataUsingEncoding(NSUTF8StringEncoding)!
        
        self.databaseQueue.inDatabase { database in
            let databaseTopicRecord = DatabaseRecord(topicId: "myTopic\(self.topicId)", bucketId: Int64(bitPattern: self.bucketId), payload: data)
            try! databaseTopicRecord.insert(database)
        }
        
        self.updateData()
        
    }
    
    func updateData() -> Void {
        
        let data = "my new sentence".dataUsingEncoding(NSUTF8StringEncoding)!
        
        let query = DatabaseRecord.filter(DatabaseRecord.topicIdColumn == "myTopic\(self.topicId)" && DatabaseRecord.bucketIdColumn == Int64(bitPattern: self.bucketId))
        
        self.databaseQueue.inDatabase { database in
            if let databaseTopicRecord = query.fetchOne(database) {
                databaseTopicRecord.payload = data
                try! databaseTopicRecord.update(database)
            }
        }
        
        self.topicId += 1
        self.bucketId += 1
        self.insertData()
        
    }
    
}

class ViewController: UIViewController {
    
    var database: Database!

    override func viewDidLoad() {
        super.viewDidLoad()

        self.database = Database()
    }

}
```

The part of the code which is leading to leaks is the one inside 'updateData' method.

![screen shot 2016-09-15 at 2 11 02 pm 2](https://cloud.githubusercontent.com/assets/1763961/18561549/5fc37d30-7b4e-11e6-86dc-36d334a00b87.png)

**Comment by craigzour** [comment] 2016-09-15 18:39
UPDATE: I ran a few more tests and I isolated one line of code which is causes the leak.

Memory leak:

```swift
let query = DatabaseRecord.filter(DatabaseRecord.topicIdColumn == "myTopic\(self.topicId)" && DatabaseRecord.bucketIdColumn == Int64(bitPattern: self.bucketId))
```

No memory leak:

```swift
let query = DatabaseRecord.filter(DatabaseRecord.topicIdColumn == "myTopic\(self.topicId)")
```

I guess there is something wrong when we use two conditions in the filter.

**Comment by craigzour** [comment] 2016-09-15 18:46
UPDATE: The leak did disappear as soon as I use SQL.

```swift
let query = DatabaseRecord.filter(sql: "topicId = ? AND bucketId = ?", arguments: ["myTopic\(self.topicId)", Int64(bitPattern: self.bucketId)])
```

**Comment by groue** [comment] 2016-09-15 19:36
Hello @craigzour

Thanks for the report, and your investigation.

Frankly, it looks like a Swift bug. The way GRDB handles conditions like `fooColumn == foo && barColumn == bar` is not really special.

Which version of Swift are you using?

**Comment by craigzour** [comment] 2016-09-15 19:43
@groue I am using Swift 2.2

**Comment by swiftlyfalling** [comment] 2016-09-15 20:04
@craigzour, @groue: I'm pretty sure that you are hitting a memory leak in Swift 2.x, caused by string interpolation in certain circumstances.

See: [example 1](https://github.com/ProcedureKit/ProcedureKit/pull/435), [example 2](https://github.com/DaveWoodCom/XCGLogger/issues/137#issuecomment-241268975).

It's a Swift 2.x bug in the Swift core library.

Unfortunately, at this point, it looks like Apple is full-steam-ahead on Swift 3 and isn't fixing any more bugs in Swift 2.x.

Luckily, this bug seems to be fixed in Swift 3.

**Comment by craigzour** [comment] 2016-09-15 20:09
@swiftlyfalling @groue Oh yeah I think you are right.

**Comment by groue** [comment] 2016-09-15 20:42
Thanks for the tip @swiftlyfalling!

@craigzour, depending on the gravity of those leaks in your application, and your planned schedule to switch to Swift 3, it may be interesting to remove string interpolations from the Swift 2.3 branch, and maybe Swift 2.2. What do you think?

**Comment by craigzour** [comment] 2016-09-15 20:51
@groue I agree with you. At least people using those versions in the future will not be impacted by the leak. On my side I am gonna switch to Swift 3 soon so I will be able to tell you if the leak has been fixed or not.

**Comment by groue** [comment] 2016-09-17 08:19
OK, so I guess this issue can be closed. It contains enough information for users who would suffer from severe leaks (the SQL workaround, and the migration to Swift 3).

**Closed by groue** 2016-09-17 08:19 UTC
Labels: blocked, bug
