### ISSUE TITLE
SQLite error 23: authorization denied. When opening database

### ISSUE THREAD

**Issue by foxware00** [groue/GRDB.swift#571] opened 2019-07-22 14:14 UTC
### What did you do?

Opened a database connection. This code has run without problems on 1000s of sessions with a very small <0.01% of users experiencing the problem. It seems opening the database fails on certain devices. From my investigation, I believe it to be part of apple backing up the database and when the user restores their device from a backup, the authentication has changed and I receive this error. This is my code for opening the Database, taken mainly for the examples. 

```
let databaseURL = try FileManager.default
        .url(for: .applicationSupportDirectory, in: .userDomainMask, appropriateFor: nil, create: true)
        .appendingPathComponent("db.sqlite")
let dbPool = try BlinkDatabase.shared.openDatabase(atPath: databaseURL.path, logging: false)
```

This is more of a question as to whether you've seen a similar problem or if I might be going down the wrong avenue. From Apples documentation I can see `.applicationSupportDirectory` will be backed-up automatically. 

I am thinking of catching this exception and deleting the database, but given it's related to a backup, might be more advisable to simply not back up the database files in the first place

If it helps I have another log from my keychain earlier in the stack `User interaction is not allowed` when trying to access keychain. I presume it's either a corrupted device or an issue with the backup

### Environment

**GRDB flavor(s):** GRDB
**GRDB version:** 4.1.1
**Installation method:** CocoaPods
**Xcode version:** 10.2
**Swift version:** 5.0
**Platform(s) running GRDB:** iOS
**macOS version running Xcode:** 10.14.5

**Comment by groue** [comment] 2019-07-23 13:26
Hello @foxware00,

> From my investigation, I believe it to be part of apple backing up the database and when the user restores their device from a backup, the authentication has changed and I receive this error.

Thanks for the investigation. I personally have only witnessed SQLite error 23 (SQLITE_AUTH) during accesses to a database locked due to data protection (background access on a locked device). I'm happy you share this other experience with all GRDB users.

> I am thinking of catching this exception and deleting the database, but given it's related to a backup, might be more advisable to simply not back up the database files in the first place

This really depends on your application needs. There is no general answer to this question, here.

> This is more of a question as to whether you've seen a similar problem or if I might be going down the wrong avenue.

I don't think you're doing anything wrong. We're just learning all the quirks of using SQLite on iOS :-)

I'll close this issue in a few days, unless you have other questions. Thanks again for sharing your experience, and make it available to search engines!

**Comment by foxware00** [comment] 2019-07-23 14:06
> Thanks for the investigation. I personally have only witnessed SQLite error 23 (SQLITE_AUTH) during accesses to a database locked due to data protection (background access on a locked device). I'm happy you share this other experience with all GRDB users.

Interestingly I did think about this, but Crashyltics seems to be reporting it in the foreground. On second thoughts clearing the Database might be a bit extreme if this is the scenario.

Many thanks for the feedback and a truly wonderful library with first-class support! Feel free to close, I'll keep an eye on it going forward.

**Closed** 2019-07-23 14:55 UTC
Labels: support

**Comment by michalraska** [comment] 2020-03-13 17:21
Hello, I had the same issue due to default [file encryption](https://developer.apple.com/documentation/uikit/protecting_the_user_s_privacy/encrypting_your_app_s_files) "`Complete until first user authentication`". An application I am working on works with a database in background and can be started by iOS on the background too (even when the user has locked phone and files are encrypted). Fix is very easy in case your persisted data do not need to be encrypted. I created the unencrypted folder and moved the database there.

```swift
...

let databaseUrlDirectory = try unprotectedDirectory()
let databaseUrl = databaseUrlDirectory.appendingPathComponent("db.sqlite")
dbQueue = try AppDatabase.openDatabase(atPath: databaseUrl.path)

...

private func unprotectedDirectory() throws -> URL {
    let url = try FileManager.default.url(
        for: .applicationSupportDirectory,
        in: .userDomainMask,
        appropriateFor: nil,
        create: true
    ).appendingPathComponent(
        "unprotected",
        isDirectory: true
    )
    if !FileManager.default.fileExists(atPath: url.path) {
        try FileManager.default.createDirectory(
            at: url,
            withIntermediateDirectories: false,
            attributes: [
                FileAttributeKey.protectionKey: URLFileProtection.none
            ]
        )
    }
    return url
}
```

Crashes caused by this issue dropped to zero.
