### ISSUE TITLE
"Redefinition of 'sqlite3_file'" error when using GRDB.swift/SQLCipher in multiple targets

### ISSUE THREAD

**Issue by ozzik** [groue/GRDB.swift#1167] opened 2022-02-03 19:06 UTC
Hey!
Apologies for double posting, but I couldn't find anything similar in existing issues or on Google 🙇 

### What did you do?
- My app uses an encrypted SQLite DB
- I'm trying to get the app's widget to also access the DB

This podfile allows the app to build:

```
target 'App' do
	use_frameworks!
	pod 'GRDB.swift', :inhibit_warnings => true
end
target 'AppWidgets' do
	use_frameworks!
	pod 'GRDB.swift', :inhibit_warnings => true
end
```

But I actually need the SQLCipher version, so I tried:

```
target 'App' do
	use_frameworks!
	pod 'GRDB.swift/SQLCipher'
	pod 'SQLCipher'#, '~> 4.0'
end
target 'AppWidgets' do
	use_frameworks!
	pod 'GRDB.swift/SQLCipher'
	pod 'SQLCipher'#, '~> 4.0'
end
```

### What did you expect to happen?

App should get built

### What happened instead?

Xcode throws build errors about "Redefinition of 'sqlite3_file'" in sqlite3.h, see this image
![Screen Shot 2022-02-03 at 9 02 47 PM](https://user-images.githubusercontent.com/3399560/152411005-2076ac37-7f48-4dfb-9f40-01ab64605b9e.png)

### Environment

**GRDB flavor(s): SQLCipher***
**GRDB version: 5.20**
**Installation method:  CocoaPods**
**Xcode version: 13.2.1 (13C100)**
**Swift version: 5 (I think)**
**Platform(s) running GRDB: iOS**
**macOS version running Xcode: 12.1 (21C52)**

Thanks a ton ✌️

**Comment by groue** [comment] 2022-02-03 19:36
Hello @ozzik, I'm not sure I can do anything. Try tweaking your Podfile, or ask in the CocoaPods repository?

**Comment by ozzik** [comment] 2022-02-03 19:45
tnx @groue, will try!

do you think installing GRDB manually and targeting the app widget might be an alternative?

**Comment by groue** [comment] 2022-02-04 10:05
Build errors are painful, @ozzik, I'm well aware. They are usually very dependent on your specific setup. And the root cause is hard to detect. Indeed, your goal is to find out where the fix should be applied. Is it in your app? In the GRDB.swift/SQLCipher pod? In the SQLCipher pod? In CocoaPods? In Xcode? Who knows? Do ask your local build guru, perform Google searches for similar error messages, and please report any progress!

**Comment by ozzik** [comment] 2022-02-04 10:10
thanks again @groue for the quick reply and help!
Kind of a bummer I can't find much on Google regarding using GRDB+SQLCipher on multiple targets (app and extension) /: will update if something comes up

**Comment by groue** [comment] 2022-02-04 10:16
> Kind of a bummer I can't find much on Google regarding using GRDB+SQLCipher on multiple targets

Oh, that was a pretty optimistic expectation. Some other people probably met a similar problem with _other libraries_, so choose your keywords wisely when you perform Google searches.

**Comment by groue** [comment] 2022-02-06 10:08
@ozzik,

I've created an iOS project with two targets, one app and one widget extension. My Podfile is:

```ruby
platform :ios, '15.2'

target 'Issue1167' do
  use_frameworks!
  pod 'GRDB.swift/SQLCipher'
  pod 'SQLCipher'
end

target 'Issue1167WidgetExtension' do
  use_frameworks!
  pod 'GRDB.swift/SQLCipher'
  pod 'SQLCipher'
end
```

And the project builds without any error.

Since you're migrated your project from 'GRDB.swift' to 'GRDB.swift/SQLCipher', you can try to:

- Check that no other dependency in your Podfile depends on 'GRDB.swift' (without SQLCipher).
- Run `pod deintegrate` before `pod install` again, in case some remnants of the previous Podfile would block.

**Comment by groue** [comment] 2022-02-15 19:33
No news is good news: I'm closing the issue. Feel free to report any progress, @ozzik. Happy GRDB!

**Closed by groue** 2022-02-15 19:33 UTC
Labels: support

**Comment by ozzik** [comment] 2022-02-17 15:00
Thanks! You're right, this does work in new projects. I can't get it to work once I add my source code but anyways giving up for now. Thanks so much regardless for the quick response and help!!
