### ISSUE TITLE
Xcode 14.2 issue !

### ISSUE THREAD

**Issue by X901** [groue/GRDB.swift#1310] opened 2023-01-03 10:21 UTC
I got this error 

```
Thread Performance Checker: Thread running at QOS_CLASS_USER_INTERACTIVE waiting on a lower QoS thread running at QOS_CLASS_BACKGROUND. Investigate ways to avoid priority inversions
PID: 75350, TID: 1552329
```

see the image below, i'm using last version 6.6.0

<img width="2203" alt="Screenshot 2023-01-03 at 1 21 01 PM" src="https://user-images.githubusercontent.com/16876982/210338709-9d2e89b5-ac63-4c98-9115-6e205680bfdb.png">

**Comment by groue** [comment] 2023-01-03 10:50
hello @X901,

Does your app has the database run at a low quality of service with an explicit `Configuration.qos` or `Configuration.targetQueue`?

**Comment by groue** [comment] 2023-01-03 12:46
> it's a legacy code how can I check if I use low quality of service ?

Check the `Configuration` value used when your app creates an instance of `DatabasePool`:

```swift
var config = Configuration()
...
let dbPool = try DatabasePool(path: somePath, configuration: config)
```

> I didn't have any warning since Xcode 12 and 13, its appear only on Xcode 14

The runtime warnings you are seeing were introduced in recent SDKs. See #1234 (fixed by #1235).

**Comment by groue** [comment] 2023-01-04 06:43
> if it's fixed the the PR merged, how I still have it when I'm on last version v6.6.0 ?

Check #1234 for some hypothesis.

> should I depend on Master branch not up to 6.6.0 ?

No, don't leave the road. The issue IS fixed.

In my current understanding, the problem is in the application, NOT in the library. The application IS accessing the database from a low-priority thread, and IS waiting for this low-priority thread from a high-priority thread. Look closely at your application code, you should be able to spot this pattern.

**Comment by groue** [comment] 2023-01-04 06:59
I'm closing this issue in favor of #1234. Please don't reply here, and add new information to #1234 if you want to share more insights, thank you!

**Closed by groue** 2023-01-04 06:59 UTC
Labels: support
