### ISSUE TITLE
Unable to save record in attached database

### ISSUE THREAD

**Issue by mallman** [groue/GRDB.swift#971] opened 2021-04-28 16:15 UTC
### What did you do?

I called the `save(_ db: Database)` method on a record associated with a table in an attached database. The `db` in this case is not a Database instance from the attached database itself. Rather, it's an instance from the database to which the other database has been attached.

### What did you expect to happen?

I expected my record to be inserted or updated in the attached database.

### What happened instead?

I received an Error:

```swift
Error: SQLite error 1: no such table: library
```

### Environment

**GRDB flavor(s):** GRDB with SQLite 3.35.5
**GRDB version:** 5.7.4
**Installation method:** Manual compile
**Xcode version:** 12.5
**Swift version:** 5.4
**Platform(s) running GRDB:** macOS
**macOS version running Xcode:** 11.3

### Further Notes

This is an issue with GRDB 5.7.0+. GRDB 5.6.0 does not exhibit this behavior. GRDB 5.6.0 saves records to attached databases successfully.

I believe commit b13922b76e8059fc57d328aa5fa7a54f0f0ac03f introduced this behavior.

It's not clear to me that this is a bug, _per se_, because GRDB makes no mention of support (or lack thereof) for attached databases. However, this is a breaking change in behavior for users who have come to rely on this behavior. Therefore, I suggest we work on a proper solution, such as documented support for attached databases from some future version.

Indeed, the comment at https://github.com/groue/GRDB.swift/blob/b13922b76e8059fc57d328aa5fa7a54f0f0ac03f/GRDB/Core/Database+Schema.swift#L10 suggests the kernel of a way forward.

I'm a little time-stretched, so I don't know if I'll be able to contribute a PR within a reasonable timeframe. Is this something @groue can take on in the near future? If not, I will have a go at it.

**Comment by groue** [comment] 2021-04-29 14:54
Hello @mallman,

I'm sorry about this regression. It will be fixed.

I indeed recently added preliminary support for schemas (only `main` and `temp`), because GRDB record types need information about the database schema. I recently had a bug where a temp table that shadows a main table would be incorrectly handled.

This change broke support for attached databases, as you can see. We'll need regression tests.

Support for attached databases is not explicitly mentioned, but it ought to be there. [SQLite can deal with unprefixed database table names](https://www.sqlite.org/lang_attach.html):

> Tables in an attached database can be referred to using the syntax `schema-name.table-name`. If the name of the table is unique across all attached databases and the main and temp databases, then the `schema-name` prefix is not required. If two or more tables in different databases have the same name and the `schema-name` prefix is not used on a table reference, then the table chosen is the one in the database that was least recently attached.

Meanwhile, I hope you can remain on GRDB 5.6.

**Comment by groue** [comment] 2021-05-01 15:24
This issue is fixed by #973

**Closed** 2021-05-16 13:26 UTC
Labels: bug
