### ISSUE TITLE
Please tag using correct semver

### ISSUE THREAD

**Issue by fpillet** [groue/GRDB.swift#368] opened 2018-06-07 14:45 UTC
To be able to use GRDB.swift from Package Manager, we need correct semantic versioning.

Meaning, instead of tagging `v3.0.0` you want to tag `3.0.0` so that SPM can automatically infer the correct version.

This is especially important since transitive dependencies cannot target anything else than the `master` branch. If you use a framework which itself uses GRDB, the embedded framework is only allowed to use semantic versioning on the master branch of GRDB and cannot use a specific branch or revision instead to fix the issue of tags not adhering to the semver conventions.

**Comment by groue** [comment] 2018-06-07 14:55
```
$ git for-each-ref --format '%(refname) %(authorname)' refs/tags
refs/tags/3.0.0-beta2 Florent Pillet
refs/tags/v0.1.0 Gwendal Roué
...
refs/tags/v2.8.0 Gwendal Roué
refs/tags/v2.9.0 Gwendal Roué
refs/tags/v3.0.0 Gwendal Roué
refs/tags/v3.0.0-beta2 Florent Pillet
```

**Regular GRDB tags start with a `v`**.

SPM is totally happy with that. But SPM breaks horribly whenever there is a mix of conventions.

I don't know how your tags has ended up in there, but they are the sources of your issues. And now the issues of everybody, since I did push them to the main GRDB repo (with some stupid git command I guess) 😅 .

I'll clean up this. And you have to start using `v`-prefixed tags whenever your tag GRDB commits.

**Comment by fpillet** [comment] 2018-06-07 14:57
Man! How did this tag end up in your repo ? Sorry about that, I'll be more careful in the future. I was supposed to have pushed this to my own remote only :(

Thanks for cleaning up my abominations, Gwendal 👍

**Comment by groue** [comment] 2018-06-07 14:59
This is a dupe of #364, actually.

I guess they came with your recent pull request, and an over-friendly git GUI (Gitbox) 😖. So it's all my fault, not yours!

Still you may need to run the following command on your local repo:

```
git tag -d 3.0.0-beta2
git tag -d v3.0.0-beta2
git push origin :refs/tags/3.0.0-beta2
git push origin :refs/tags/v3.0.0-beta2
```

**Comment by groue** [comment] 2018-06-07 15:12
This should be fixed now! Does everything works for you Florent?

**Comment by fpillet** [comment] 2018-06-07 15:13
Yes, works great, thanks for the fast fix!!

**Closed** 2018-06-07 15:15 UTC
Labels: bug

**Comment by klaas** [comment] 2018-06-17 21:49
Yet again, SPM support is broken because of this :(

Certainly SPM should fix this as well.

**Comment by groue** [comment] 2018-06-18 05:16
Thanks @klaas. 😒 Something is broken in my workflow...

**Comment by klaas** [comment] 2018-06-18 08:36
My fork is clean for now 😃 I would rather deploy to our production systems with the main repo though:)

**Comment by groue** [comment] 2018-06-18 08:38
I'll do something about it. Sincere apologies.

**Comment by klaas** [comment] 2018-06-18 10:03
I'm so happy with GRDB that there is no need to apologise! By now I know what to do :)
