### ISSUE TITLE
Join two instances of QueryInterfaceRequest<RowDecoder> on a join condition

### ISSUE THREAD

**Issue by mallman** [groue/GRDB.swift#1207] opened 2022-04-22 15:54 UTC
I'd like to be able to join two instances of `QueryInterfaceRequest<RowDecoder>` on a general join condition.

I added the following extension method, and it has worked for me so far:

```swift
extension QueryInterfaceRequest {
    public func association<Destination>(
        to queryInterfaceRequest: QueryInterfaceRequest<Destination>,
        on condition: @escaping (_ left: TableAlias, _ right: TableAlias) -> SQLExpressible)
    -> JoinAssociation<RowDecoder, Destination>
    {
        JoinAssociation(
            to: queryInterfaceRequest.relation,
            condition: .expression { condition($0, $1).sqlExpression })
    }
}
```

Could it be this easy? 🤔

This implementation is inspired by the nascent support for join associations between tables and common table expressions in GRDB.

I think we can similarly support joins between two `Table<RowDecoder>` instances.

### Environment

**GRDB flavor(s):** Custom
**GRDB version:** 5.21.0
**Installation method:** manual
**Xcode version:** 13.3.1
**Swift version:** 5.6
**Platform(s) running GRDB:** macOS
**macOS version running Xcode:** 12.3.1

**Comment by groue** [comment] 2022-04-22 16:30
Hello @mallman,

Yes, it should be as easy :-)

This was done for the CTE support indeed. And to prepare support for "universal joins" (that you are looking for).

I hope this is not public yet, though, because there are limitations. For exemple I think that `record.request(for: thisAssociation)` fatal errors when given such an association. There are maybe other fatal errors lurking. Only CTEs have been vetted.

**Comment by mallman** [comment] 2022-04-22 20:10
I'm glad you're amenable to my request. :)

I'm not sure what you're referring to when you write "I hope this is not public yet".

I intend to keep this functionality as a private patch on the official codebase. I will let you know what kind of issues I run into.

One thing I have had a problem with is if I don't give a specific name to a `TableAlias` I use in a join, I get a fatal error about an undefined table alias. If I provide a table alias name then I don't have this issue, and the join is performed correctly. I'm not sure if this is an issue in the way I'm using the table aliases or if its a problem in GRDB (or my patch thereof).

**Comment by groue** [comment] 2022-04-22 20:33
I'm not sure either. You're definitely visiting a draft.

The trouble with associations is that they are at the root of a huge combinatorial explosion of use cases. The api is recursive (you can jump from associations to other associations), and this means that exploring all the combinations the users can come up with is hard. Designing tests that thoroughly explore this space is very difficult.

I'm not surprised you meet unexpected behaviors. My only hope is that this is fixable.

Since you're visiting uncharted territories, your detailed feedback is very precious. If you try to understand what is happening, and maybe even suggest where things derail and should be fixed, that's even better. Arguably we're not in an easy GRDB area. I can help, but we'd need to discuss GRDB internals for good.

**Comment by groue** [comment] 2022-04-26 07:28
Hi @mallman, should we keep this issue open?

**Comment by mallman** [comment] 2022-04-27 17:16
> Hi @mallman, should we keep this issue open?

Hi @groue. My interest in (and use of) this feature remains. I would ask that we keep this open unless you decide GRDB will not implement this feature, or if this issue may be subsumed under a broader issue regarding join support for arbitrary join conditions.

I've been using this feature successfully so far, except, as I've mentioned before, the fact that I get an error when using a `TableAlias` unless I pass a name to the constructor.

My usage is getting more complex, so I can provide more feedback later. Unfortunately, I don't know how much time I'll have for that this week.

One thing I haven't tried yet is a self join. These can be a tricky edge case. I will report back with my experience on that when I encounter that scenario.

**Comment by groue** [comment] 2022-04-27 18:14
> My usage is getting more complex, so I can provide more feedback later.

Sounds good!

Please note that I'm not currently investigating the topic.

I see "universal joins" as a nice feature, but they are not in my personal todo-list. They may even be a bad idea, when we consider that associations are designed for people who don't speak SQL.

Sure, associations are also a convenience for SQL-speaking people. But for other users, they are the _only_ api that can be more efficient than their uninformed code. Because of the target population, associations expose a very rich set of apis, and it is very much possible that some of those apis _can not_ support universal joins.

This means that shoehorning the support for any kind of joins into associations might reveal difficult, or even impossible: be ready for a dead-end 😬 

But I'm optimistic! So we'll keep the issue open for a while. I'll jump in when you need help merging your changes upstream. Or we'll close the issue if nothing happens.

If you want to merge your changes, it will be appreciated if you had evaluated the needed work, and are ready to perform some of it. I know it's not easy, but as I tried to explain above, "universal joins" is a big feature, that opens a lot of use cases. It will need a lot of tests.

"Universal joins" is the kind of feature where a "works on my machine", "works in my app", or "please just finish it" attitude won't pass the threshold, given the known risk that the idea is just a dead-end.

The three key skills here are _empathy_ for the future users of your feature, a rich _imagination_, and the ability to _actively_ search for failures and edges cases. The widest range of possible use cases, and combination of GRDB apis, should be explored, and tested. Some bugs can slip through, of course, because users are always wilder than we think 🤘 

Maybe you'll be able to _shrink_ the feature, from "Universal joins" to something smaller and more manageable? That's how I could ship them for CTEs.

Maybe "an error when using a `TableAlias` unless I pass a name to the constructor" is a latent GRDB bug that should be fixed on its own, right away?

I'm curious!

**Comment by mallman** [comment] 2022-05-05 20:08
> "Universal joins" is the kind of feature where a "works on my machine", "works in my app", or "please just finish it" attitude won't pass the threshold, given the known risk that the idea is just a dead-end.

We are in agreement on this matter.

> Maybe you'll be able to shrink the feature, from "Universal joins" to something smaller and more manageable? That's how I could ship them for CTEs.

That's something to consider.

> Maybe "an error when using a TableAlias unless I pass a name to the constructor" is a latent GRDB bug that should be fixed on its own, right away?

I agree, however I've never seen this problem before I started seeing it in my new, exotic use of the API. It's possible that I'm "abusing" it in a way that would be considered poor practice or invalid usage. Though I have tried to debug the cause of this failure, I have not been able to get to the bottom of it.

As it happens, I've been helping bring a major new product for the company I work for to GA the past couple of weeks, and it has nothing to do with GRDB. The product is now over a month past our promised delivery date, and I'm working full days, 7 days a week now. Which is to say I'm sorry I haven't responded sooner, but I have a really good excuse.

I'll come back to this when I have time for my own projects again, hopefully late next week.

**Comment by groue** [comment] 2022-05-06 04:41
I'm relieved by your answer, because I was afraid my words sounded too much like a rebuttal. Experimental code is very welcome, but sometimes it is hard to merge it right away.

Maybe we should find something between the stable release and your individual fork. We could work in a dedicated GRDB branch.

> I agree, however I've never seen this problem before I started seeing it in my new, exotic use of the API. It's possible that I'm "abusing" it in a way that would be considered poor practice or invalid usage. Though I have tried to debug the cause of this failure, I have not been able to get to the bottom of it.

If you can share a small reproducing code, I can have a look.

**Comment by groue** [comment] 2022-05-16 09:07
Hello @mallman. I don't like issues to stay open when nobody is working on them, so I'll close it. Please come back with something to chew on when you're ready :-)

**Closed by groue** 2022-05-16 09:07 UTC
Labels: enhancement

**Comment by mallman** [comment] 2022-05-16 14:15
I was going to close this issue soon, probably this week, for lack of a plan. I will revisit it if/when I have a more complete proposal for an API.

Incidentally, regarding the issue with the invalid `TableAlias` when not specifying a name, I have good news and bad news. The good news is I'm unable to reproduce the issue. The bad news is I'm unable to reproduce the issue.

This is with the same version of GRDB as before. I don't know what change in my codebase made the difference. I tried to reproduce the issue this morning with the intention of digging deeper, and the dang thing wouldn't fail. Oh well. Maybe it will fail again in the future.

**Comment by groue** [comment] 2022-05-16 15:52
> I was going to close this issue soon, probably this week, for lack of a plan. I will revisit it if/when I have a more complete proposal for an API.

I'll be there for you!

> Incidentally, regarding the issue with the invalid `TableAlias` when not specifying a name, I have good news and bad news. The good news is I'm unable to reproduce the issue. The bad news is I'm unable to reproduce the issue.

🤣

> This is with the same version of GRDB as before. I don't know what change in my codebase made the difference. I tried to reproduce the issue this morning with the intention of digging deeper, and the dang thing wouldn't fail. Oh well. Maybe it will fail again in the future.

Let's just wait until it comes back :-) Thank you for your patience Michael!
