### ISSUE TITLE
Cocoapods hasn't published since 6.24.1

### ISSUE THREAD

**Issue by KeithBauerANZ** [groue/GRDB.swift#1522] opened 2024-04-03 22:20 UTC
Only versions up to 6.24.1 are available in Cocoapods (6.24.2, 6.25.0, 6.26.0 are missing as of time of writing).

(We still need Cocoapods because it seems like SQLCipher isn't supported by Package.swift?)

**Comment by groue** [comment] 2024-04-04 01:06
Duplicate of #1518

**Comment by groue** [comment] 2024-04-04 01:06
Since you need SQLCipher, @KeithBauerANZ, please have a look at https://github.com/groue/GRDB.swift/discussions/1495

**Closed as completed by groue** 2024-04-04 01:06 UTC
Labels: duplicate
