### ISSUE TITLE
Get new autoincremented Id after each insert statement  

### ISSUE THREAD

**Issue by zefender** [groue/GRDB.swift#914] opened 2021-01-29 19:10 UTC
### What did you do?

Hi! Please help me!

Here is my scheme 
```
CREATE TABLE word (
    id              INTEGER PRIMARY KEY AUTOINCREMENT,
    text            TEXT    NOT NULL,
    example         TEXT    DEFAULT NULL,
    definition      TEXT    NOT NULL,
    transcription   TEXT    NOT NULL,
    sampleId        TEXT    NOT NULL
);

CREATE TABLE translation (
    id      INTEGER PRIMARY KEY AUTOINCREMENT,
    text    TEXT    NOT NULL
);

CREATE TABLE wordTranslation (
    id             INTEGER PRIMARY KEY AUTOINCREMENT,
    wordId         INTEGER NOT NULL,
    translationId  INTEGER NOT NULL,
    isCorrect      INTEGER NOT NULL,
    FOREIGN KEY(translationId) REFERENCES translation(id),
    FOREIGN KEY(wordId) REFERENCES word(id)
);
CREATE INDEX idx_wordTranslation_wordId ON wordTranslation (wordId);
CREATE INDEX idx_wordTranslation_translationId ON wordTranslation (translationId);

CREATE TABLE collection (
    id              INTEGER PRIMARY KEY AUTOINCREMENT,
    name            TEXT    NOT NULL
);

```

I'm trying to do pretty simple stuff, insert few associated rows into tables.
```
func insertCustomWord(text: String, translation: String, example: String, definition: String) {
        var newWordId: Int64 = 0
        var newTranslationId: Int64 = 0
        
        try! db.write { db in
            // Insert word
            let insertWordQuery = """
            insert into word(text, example, definition, transcription,  sampleId, frequency, isFavorite, isCustom)
            values (:text, :example, :definition, :transcription, :sampleId, :frequency, :isFavorite, :isCustom)
        """
            
            try db.execute(sql: insertWordQuery,
                           arguments: StatementArguments(["text": text,
                                                          "example": example,
                                                          "definition": definition,
                                                          "transcription": " ",
                                                          "sampleId": " ",
                                                          "frequency": 7,
                                                          "isFavorite": 0,
                                                          "isCustom": 1]))
            
            newWordId = db.lastInsertedRowID
        }
        
        try! db.write { db in
            let inserTranslationQuery = """
                insert into translation(text)
                values ('someeee')
            """
            
            try db.execute(sql: inserTranslationQuery,
                           arguments: StatementArguments(["translation": translation]))
            
            newTranslationId = db.lastInsertedRowID
        }
        
        try! db.write { db in
            let insertCorrectTranslationQuery = """
                insert into wordTranslation(wordId, translationId, isCorrect)
                values(:wordId, :translationId, :isCorrect)
            """
            
            // Correct translation
            try db.execute(sql: insertCorrectTranslationQuery,
                           arguments: StatementArguments(["wordId": newWordId,
                                                          "translationId": newTranslationId,
                                                          "isCorrect": 1]))
        }
    }
```

### What did you expect to happen?

I expect db.lastInsertedRowID gives me a new inserted ID after each insert query. I need it to insert as a foreign key value into next table. I've also tried to do it in a single  `db.write { db in` statement

### What happened instead?

Each time I call db.lastInsertedRowID I get the same value.

Thank you!

### Environment

**GRDB flavor(s):** GRDB
**GRDB version:** latest, I'v updated it just before making an issue here
**Installation method:** CocoaPods
**Xcode version:** 12.3
**Swift version:** 5.3
**Platform(s) running GRDB:** iOS
**macOS version running Xcode:** Big Sur 11.1

**Comment by mregnauld** [comment] 2021-01-29 19:17
Not sure if it helps, but you can use Swift instead of pure SQL to create your table.
You can check [here](https://github.com/groue/GRDB.swift/blob/master/Documentation/AssociationsBasics.md#convention-for-the-hasmany-association) for an example

**Comment by groue** [comment] 2021-01-29 19:58
Hello @zefender 

> I expect db.lastInsertedRowID gives me a new inserted ID after each insert query. 

Good expectation!

> Each time I call db.lastInsertedRowID I get the same value.

Row ids are incremented table per table, so you'll get 1 for the first insertion into `word`, and 1 as well for the first insertion into `translation`. But for the second insertion into `word`, you'll get 2. Etc. 

This is a very well tested feature of SQLite and GRDB.

If you are really sure you found a wrong behavior, please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example), thank you!

**Comment by groue** [comment] 2021-01-29 20:00
> Not sure if it helps, but you can use Swift instead of pure SQL to create your table.
> You can check here for an example
> That's what I do in my project, and it works fine.

Thank you @mregnauld! Raw SQL is fine, you know. GRDB allows you to avoid it, but people who prefer to write SQL are welcomed just as well. Those table creation requests look just fine.

**Comment by zefender** [comment] 2021-01-30 10:06
> Not sure if it helps, but you can use Swift instead of pure SQL to create your table.
> You can check [here](https://github.com/groue/GRDB.swift/blob/master/Documentation/AssociationsBasics.md#convention-for-the-hasmany-association) for an example
> That's what I do in my project, and it works fine.

Thanks for your reply! I prefer to stick with raw SQL to avoid one more abstraction level and also keep my domain model objects as a simple struct framework independent. Sometimes I have to create very complex select statements, so it's easy to me.

**Comment by zefender** [comment] 2021-01-30 10:09
> Hello @zefender
> 
> > I expect db.lastInsertedRowID gives me a new inserted ID after each insert query.
> 
> Good expectation!
> 
> > Each time I call db.lastInsertedRowID I get the same value.
> 
> Row ids are incremented table per table, so you'll get 1 for the first insertion into `word`, and 1 as well for the first insertion into `translation`. But for the second insertion into `word`, you'll get 2. Etc.
> 
> This is a very well tested feature of both SQLite and GRDB.
> 
> If you are really sure you found a wrong behavior, please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example), thank you!

Thank your for quick feedback! 
You gave me and idea to check actual values of primary keys in my tables, it might just be equal by chance! 
And what's better approach for this classic scenario "Insert related rows in one turn"? Should I use single write closure or multiple?

**Comment by groue** [comment] 2021-01-30 10:31
> Should I use single write closure or multiple?

The rule 2 of the [Concurrency Guide](https://github.com/groue/GRDB.swift/blob/master/README.md#concurrency) is:

> Group related statements within a single call to a DatabaseQueue or DatabasePool database access method.

So the answer to your question is yes. You'll gain two advantages:

- Your changes will be committed all together, on not at all (because writes are embedded in a transaction). So you will never a database which is only partially updated.
- Concurrent reads or writes won't see partial updates, and this will avoid multi-threading bugs (if your app happens to access the database from various threads, eventually).

**Comment by zefender** [comment] 2021-01-30 10:34
Thank you, it's clear now. I'll check my primary keys again

**Comment by zefender** [comment] 2021-01-30 10:35
It's even would be better to do it in Rx way, any advice on it?

**Comment by groue** [comment] 2021-01-30 10:42
> It's even would be better to do it in Rx way, any advice on it?

I don't have any particular advice, no :-) You can use GRDB with or without RxSwift or Combine. This is up to you, your preferences, your skills, your experience, etc. GRDB will help equally.

**Comment by groue** [comment] 2021-02-03 07:21
It looks like autoincremented ids work as expected: I close the issue. Happy GRDB!

**Closed by groue** 2021-02-03 07:21 UTC
Labels: support
