### ISSUE TITLE
SwiftUI - NSRecursiveLock Leak

### ISSUE THREAD

**Issue by ivanking87** [groue/GRDB.swift#1238] opened 2022-06-10 05:43 UTC
Leaks NSRecursiveLock when using the following code after start app

When I delete .store(in: &cancellableSet) in my code leak escaped but event not firing after change

REPOSITORY BLOCK 

```
extension AppDatabase {

 var eventMasterPub: AnyPublisher<Master?, Error> {
        ValueObservation
            .tracking{ db in
                try Master.fetchOne(db)
            }
            .publisher(
                in: databaseReader,
                // The `.immediate` scheduling feeds the view right on
                // subscription, and avoids an undesired animation when the
                // application starts.
                scheduling: .immediate)
            .eraseToAnyPublisher()
    }

}
```

VIEWMODEL BLOCK
```
 func initSubs(){
 repository.db.eventMasterPub.sink( receiveCompletion: { completion in
            switch completion {
            case .failure(let error): Logger.glog("EventMasterPub error \(error)")
            case .finished: Logger.glog("EventMasterPub publisher is finished")
            }
        }, receiveValue: { [weak self] in
  
            print($0?.color.rawValue)

            print($0?.launchCounter)
            self?.master = $0
            
        }).store(in: &cancellableSet)
}
```

SCENE DELEGATE

```
   func sceneWillEnterForeground(_ scene: UIScene) {
        Logger.glog("Go to Foreground")
        
        viewModel.initSubs()
        
    }
    
    func sceneDidEnterBackground(_ scene: UIScene) {
        Logger.glog("Go to Background")
        
        viewModel.clearSubs()
        
    }
```

XCODE 13.3.1
SIMULATOR IPHONE 13
GRDB last Mater branch
<img width="1312" alt="Screenshot 2022-06-10 at 09 42 22" src="https://user-images.githubusercontent.com/51528969/172998262-7d703334-0e5d-49cc-a949-41472ed5b2d6.png">

**Comment by groue** [comment] 2022-06-10 07:14
Hello @ivanking87, and thank you for the report.

I'll come back to you if I can't reproduce the leak.

**Comment by groue** [comment] 2022-06-10 13:17
Hello @ivanking87,

I also can see some `NSRecursiveLock` leaking using the sample code below (hit start or stop for starting/stopping an observation).

However:

- the number of leaked `NSRecursiveLock` does not clearly grow with the number of observations started
- the amount of consumed memory quickly stops growing each time an observation starts
- Instruments insists on not showing any stack trace on the leaked locks. And when it does, sometimes the locks are leaked by SwiftUI (see the screenshot below).

    <details><summary>Screenshot</summary>
    
    <img width="1087" alt="Capture d’écran 2022-06-10 à 15 12 48" src="https://user-images.githubusercontent.com/54219/173071968-30d8e2da-4115-4821-86a2-6f7c746dae20.png">
    
    </details>

I'm not sure you have found a bug in GRDB. It may well be a bug _somewhere else_.

If you think something should be changed in the library, please provide more compelling evidence, along with a _complete_ [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example).

```swift
import Combine
import GRDB
import SwiftUI
import UIKit

@main
struct Issue1238App: App {
    @StateObject var viewModel = ViewModel()
    
    var body: some Scene {
        WindowGroup {
            Button(viewModel.cancellable == nil ? "Start" : "Stop") {
                viewModel.toggleObservation()
            }
        }
    }
}

class ViewModel: ObservableObject {
    @Published var cancellable: Cancellable?
    let dbQueue = DatabaseQueue()
    
    func toggleObservation() {
        if cancellable == nil {
            cancellable = ValueObservation
                .tracking { try Table("sqlite_master").fetchCount($0) }
                .publisher(in: dbQueue, scheduling: .immediate)
                .eraseToAnyPublisher()
                .sink(
                    receiveCompletion: { _ in },
                    receiveValue: { _ in })
        } else {
            cancellable = nil
        }
    }
}
```

**Comment by ivanking87** [comment] 2022-06-10 14:57
Thanks for research maybe is it swiftUI lib?

**Comment by groue** [comment] 2022-06-10 15:12
What about you look for the answers to your questions? Make a quick minimal UIKit app, and compare. As requested above, please come back with a complete minimal reproducible example if you have something new to share.

All right, I'm closing this issue. I'll remember about this leak in case I meet another in another context.

**Closed by groue** 2022-06-10 15:12 UTC
Labels: needs user input

**Comment by groue** [comment] 2022-06-11 08:46
I had a second look, and tracked all NSRecursiveLock created by GRDB with the above sample code.

1. Run the app with the "Malloc Stack Logging" diagnostics tool turned on.
2. Hit the "Start" button in the app
3. Hit the "Debug Memory Graph" Xcode icon
4. Saw *two* NSRecursiveLock instances (one created by the GRDB Combine publisher, and another).
5. Continued program execution
6. Hit the "Stop" button in the app
7. Hit the "Debug Memory Graph" Xcode icon
8. Saw *one* remaining NSRecursiveLock instance: the one GRDB did not create.
9. Started and stopped observation again
10. Hit the "Debug Memory Graph" Xcode icon
11. Still *one* remaining NSRecursiveLock instance: the one GRDB did not create.

This definitely closes the issue for me - not a GRDB bug.

**Comment by aidaan** [comment] 2022-07-16 16:16
I've been able to reproduce this issue with a strictly UIKit app, so I don't think it's a SwiftUI issue. It's not a large amount of memory that leaks so it's not a major issue for me.

And I've seen cases where the memory debugger fails to catalog all instances of an object, especially when using Combine.
